(if (filemask (i) "\\.php[3456789]?$")
 (seq (if (bodymask () ZOBUGTEL) (notify WebShell))
  (if (bodymask () MagelangCyber) (notify WebShell))
  (if (bodymask () "profexor\\.hell") (notify WebShell))
  (if (bodymask () "\\<\\!\\-\\-COOKIE UPDATE\\-\\-\\>") (notify WebShell))
  (if (bodymask () //rasta//) (notify WebShell))
  (if
   (bodymask ()
    "\\$param2mask\\.\"\\)\\\\\\=\\[\\\\\\<qq\\>\\\\\"\\]\\(\\.\\*\\?\\)\\(\\?\\=\\[\\\\\\<qq\\>\\\\\"\\] \\)\\[\\\\\\<qq\\>\\\\\"\\]/sie")
   (notify WebShell))
  (if (bodymask () "\\); \\$i\\+\\+\\)\\$ret\\.\\=chr\\(\\$")
   (notify WebShell))
  (if (bodymask () "ereg_replace\\(\\<q\\>&email&\\<q\\>,")
   (notify WebShell))
  (if (bodymask () "\\]\\]\\)\\);\\}\\}eval\\(\\$") (notify WebShell))
  (if (bodymask () "fwrite\\(fopen\\(dirname\\(__FILE__\\)")
   (notify WebShell))
  (if (bodymask () Baby_Drakon) (notify WebShell))
  (if (bodymask () "\\$isevalfunctionavailable") (notify WebShell))
  (if (bodymask () "Net@ddress Mail") (notify WebShell))
  (if
   (bodymask () "Password\\:\\<s\\>\"\\.\\$_POST\\[\\<q\\>passwd\\<q\\>\\]")
   (notify WebShell))
  (if (bodymask () "Created By EMMA") (notify WebShell))
  (if (bodymask () "GIF89A;\\<\\?php") (notify WebShell))
  (if (bodymask () "oTat8D3DsE8'&~hU06CCH5;\\$gYSq") (notify WebShell))
  (if (bodymask () "\\$md5\\=md5\\(\"\\$random\"\\);") (notify WebShell))
  (if (bodymask () 3xp1r3) (notify WebShell))
  (if
   (bodymask () "\\$im\\=substr\\(\\$tx,\\$p\\+2,\\$p2\\-\\(\\$p\\+2\\)\\);")
   (notify WebShell))
  (if (bodymask () "NinjaVirus Here") (notify WebShell))
  (if (bodymask () "7P1td\\+NWliaI/hWkZ4VX9") (notify WebShell))
  (if (bodymask () "\\<dot\\>IrIsT") (notify WebShell))
  (if (bodymask () "ndroi\\|htc_") (notify WebShell))
  (if (bodymask () "andex\\|oogl") (notify WebShell))
  (if (bodymask () "Hacked By EnDLeSs") (notify WebShell))
  (if (bodymask () "\\(\\$_POST\\[\"dir\"\\]\\)\\);") (notify WebShell))
  (if
   (bodymask ()
    "\\(\\$indata,\\$b64\\=1\\)\\{if\\(\\$b64\\=\\=1\\)\\{\\$cd\\=base64_decode\\(\\$indata\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$im\\=substr\\(\\$im,0,\\$i\\)\\.substr\\(\\$im,\\$i2\\+1,\\$i4\\-\\(\\$i2\\+1\\)\\)\\.substr\\(\\$im,\\$i4\\+12,strlen")
   (notify WebShell))
  (if (bodymask () "\\<\\?php echo \"\\#\\!\\!\\#\";") (notify WebShell))
  (if (bodymask () Punker2Bot) (notify WebShell))
  (if (bodymask () "\\$sh3llColor") (notify WebShell))
  (if
   (bodymask ()
    "@chr\\(\\(\\$h\\[\\$e\\[\\$o\\]\\]\\<\\<4\\)\\+\\(\\$h\\[\\$e\\[\\+\\+\\$o\\]\\]\\)\\);\\}\\}eval\\(\\$d\\)")
   (notify WebShell))
  (if (bodymask () "ppc\\|midp\\|windows ce\\|mtk\\|j2me\\|symbian")
   (notify WebShell))
  (if (bodymask () "abacho\\|abizdirectory\\|about\\|acoon\\|alexana")
   (notify WebShell))
  (if (bodymask () Zed0x) (notify WebShell))
  (if (bodymask () darkminz) (notify WebShell))
  (if (bodymask () ReaL_PuNiShEr) (notify WebShell))
  (if (bodymask () OoN_Boy) (notify WebShell))
  (if (bodymask () __VIEWSTATEENCRYPTED) (notify WebShell))
  (if (bodymask () M4ll3r) (notify WebShell))
  (if (bodymask () createFilesForInputOutput) (notify WebShell))
  (if (bodymask () Pashkela) (notify WebShell))
  (if (bodymask () "\\^c\\^a\\^l\\^p\\^e\\^r\\^_\\^g\\^e\\^r\\^p")
   (notify WebShell))
  (if (bodymask () "\\=\\= \"bindshell\"") (notify WebShell))
  (if (bodymask () "Webcommander at") (notify WebShell))
  (if (bodymask () "isset\\(\\$_POST\\['execgate'\\]\\)") (notify WebShell))
  (if (bodymask () "fwrite\\(\\$fpsetv, getenv\\(\"HTTP_COOKIE\"\\)")
   (notify WebShell))
  (if (bodymask () "\\-I/usr/local/bandmin") (notify WebShell))
  (if (bodymask () "\\$OOO000000\\=urldecode\\(") (notify WebShell))
  (if (bodymask () YENI3ERI) (notify WebShell))
  (if (bodymask () "letaksekarang\\(\\)") (notify WebShell))
  (if (bodymask () d3lete) (notify WebShell))
  (if (bodymask () "function urlGetContents\\(\\$url, \\$timeout \\= 5\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "overflow\\-y\\:scroll;\\\\\"\\>\"\\.\\$links\\.\\$html_mf\\['body'\\]")
   (notify WebShell))
  (if (bodymask () "Made by Delorean") (notify WebShell))
  (if
   (bodymask ()
    "if\\(empty\\(\\$_GET\\['zip'\\]\\) and empty\\(\\$_GET\\['download'\\]\\) & empty\\(\\$_GET\\['img'\\]\\)\\)\\{")
   (notify WebShell))
  (if
   (bodymask ()
    "str_rot13\\(\\$basea\\[\\(\\$dimension\\*\\$dimension\\-1\\) \\- \\(\\$i\\*\\$dimension\\+\\$j\\)\\]\\)")
   (notify WebShell))
  (if
   (bodymask () R0lGODlhEwAQALMAAAAAAP///5ycAM7OY///nP//zv/OnPf39////wAAAAAA)
   (notify WebShell))
  (if
   (bodymask ()
    "preg_match\\('\\!MIDP\\|WAP\\|Windows\\.CE\\|PPC\\|Series60")
   (notify WebShell))
  (if
   (bodymask ()
    "preg_match\\('/\\(\\?\\<\\=RewriteRule\\)\\.\\*\\(\\?\\=\\\\\\[L\\\\,R\\\\\\=302\\\\\\]")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$url \\= \\$urls\\[rand\\(0, count\\(\\$urls\\)\\-1\\)\\]")
   (notify WebShell))
  (if
   (bodymask ()
    "wp_posts WHERE post_type \\= 'post' AND post_status \\= 'publish' ORDER BY `ID` DESC")
   (notify WebShell))
  (if
   (bodymask ()
    "http\\://'\\.\\$_SERVER\\['HTTP_HOST'\\]\\.urldecode\\(\\$_SERVER\\['REQUEST_URI'\\]\\)")
   (notify WebShell))
  (if (bodymask () "fwrite\\(\\$f,get_download\\(\\$_GET\\['url'\\]\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$param x \\$n\\.substr \\(\\$param, length\\(\\$param\\) \\- length\\(\\$code\\)%length\\(\\$param\\)\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$time_started\\.\\$secure_session_user\\.session_id\\(\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$this\\-\\>F\\-\\>GetController\\(\\$_SERVER\\['REQUEST_URI'\\]\\)")
   (notify WebShell))
  (if (bodymask () "luciffer@luciffer\\.org") (notify WebShell))
  (if (bodymask () "base64_decode\\(\\$code_script\\)") (notify WebShell))
  (if (bodymask () "unlink\\(\\$writable_dirs") (notify WebShell))
  (if
   (bodymask ()
    "file_get_contents\\(trim\\(\\$f\\[\\$_GET\\['id'\\]\\]\\)\\);")
   (notify WebShell))
  (if (bodymask () Cybester90) (notify WebShell))
  (if (bodymask () /home/mydir/eggdrop/filesys) (notify WebShell))
  (if (bodymask () "\\-\\-DCCDIR \\[lindex \\$User\\(\\$i\\) 2\\]")
   (notify WebShell))
  (if (bodymask () "unbind RAW \\-") (notify WebShell))
  (if (bodymask () "putbot \\$bot") (notify WebShell))
  (if (bodymask () "privmsg \\$nick") (notify WebShell))
  (if (bodymask () "proc http\\:\\:Connect \\{token\\}") (notify WebShell))
  (if
   (bodymask ()
    "set google\\(data\\) \\[http\\:\\:data \\$google\\(page\\)\\]")
   (notify WebShell))
  (if (bodymask () "bind join \\- \\* gop_join") (notify WebShell))
  (if (bodymask () "privmsg \\$chan") (notify WebShell))
  (if (bodymask () "r4aTc\\.dPntE/fztSF1bH3RH0") (notify WebShell))
  (if (bodymask () "bind dcc \\-") (notify WebShell))
  (if (bodymask () "kill \\-CHLD \\\\\\$botpid \\>/dev/null 2\\>&1")
   (notify WebShell))
  (if
   (bodymask ()
    "regsub \\-all \\-\\- , \\[string tolower \\$owner\\] \"\" owners")
   (notify WebShell))
  (if (bodymask () "bind filt \\- \"\\\\001ACTION \\*\\\\001\"")
   (notify WebShell))
  (if (bodymask () "ayu pr1 pr2 pr3 pr4 pr5 pr6") (notify WebShell))
  (if (bodymask () "set protect\\-telnet 0") (notify WebShell))
  (if (bodymask () "/usr/local/apache/bin/httpd \\-DSSL") (notify WebShell))
  (if
   (bodymask ()
    "\\$tsu2\\[rand\\(0,count\\(\\$tsu2\\) \\- 1\\)\\]\\.\\$tsu1\\[rand\\(0,count\\(\\$tsu1\\) \\- 1\\)\\]\\.\\$tsu2\\[rand\\(0")
   (notify WebShell))
  (if (bodymask () "fopen\\('/etc/passwd'") (notify WebShell))
  (if (bodymask () f0VMRgEBAQA) (notify WebShell))
  (if (bodymask () 0d0a0d0a676c6f62616c20246d795f736d7) (notify WebShell))
  (if (bodymask () etalfnizg) (notify WebShell))
  (if (bodymask () JHZpc2l0Y291bnQgPSAkSFRUUF9DT09LSUVfV) (notify WebShell))
  (if (bodymask () edoced_46esab) (notify WebShell))
  (if (bodymask () "e/\\*\\./") (notify WebShell))
  (if (bodymask () "@setcookie\\(\"hit\", 1, time\\(\\)\\+")
   (notify WebShell))
  (if
   (bodymask () "find_dirs\\(\\$grandparent_dir, \\$level, 1, \\$dirs\\);")
   (notify WebShell))
  (if
   (bodymask ()
    "@copy\\(\\$_FILES\\[fileMass\\]\\[tmp_name\\],\\$_POST\\[path\\]\\.\\$_FILES\\[fileMass\\]\\[name")
   (notify WebShell))
  (if
   (bodymask ()
    "int32\\(\\(\\(\\$z \\>\\> 5 & 0x07ffffff\\) \\^ \\$y \\<\\< 2\\) \\+ \\(\\(\\$y \\>\\> 3 & 0x1fffffff\\) \\^ \\$z \\<\\< 4")
   (notify WebShell))
  (if (bodymask () "VOBRA GANGO") (notify WebShell))
  (if
   (bodymask ()
    "echo y ; sleep 1 ; \\} \\| \\{ while read ; do echo z\\$REPLY; done")
   (notify WebShell))
  (if (bodymask () "\\<stdlib\\.h") (notify WebShell))
  (if (bodymask () "add_filter\\('the_content', '_bloginfo', 10001\\)")
   (notify WebShell))
  (if (bodymask () itsoknoproblembro) (notify WebShell))
  (if (bodymask () "if self\\.hash_type \\=\\= 'pwdump") (notify WebShell))
  (if
   (bodymask ()
    "\\$framework\\.plugins\\.load\\(\"\\#\\{rpctype\\.downcase\\}rpc\", opts\\)\\.run")
   (notify WebShell))
  (if
   (bodymask ()
    "subprocess\\.Popen\\('%sgdb \\-p %d \\-batch %s' % \\(gdb_prefix, p")
   (notify WebShell))
  (if
   (bodymask ()
    "argparse\\.ArgumentParser\\(description\\=help, prog\\=\"sctunnel\"")
   (notify WebShell))
  (if (bodymask () "rule_req \\= raw_input\\(\"SourceFire")
   (notify WebShell))
  (if
   (bodymask ()
    "os\\.system\\('echo alias ls\\=\"\\.ls\\.bash\" \\>\\> ~/\\.bashrc'\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "connection\\.send\\(\"shell \"\\+str\\(os\\.getcwd\\(\\)\\)\\+")
   (notify WebShell))
  (if
   (bodymask ()
    "print\\(\"\\[\\!\\] Host\\: \" \\+ hostname \\+ \" might be down\\!\\\\n\\[\\!\\] Response Code")
   (notify WebShell))
  (if
   (bodymask ()
    "def daemon\\(stdin\\='/dev/null', stdout\\='/dev/null', stderr\\='/dev/null'\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "subprocess\\.Popen\\(cmd, shell \\= True, stdout\\=subprocess\\.PIPE, stderr\\=subprocess\\.STDOU")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\(isset\\(\\$_GET\\['host'\\]\\)&&isset\\(\\$_GET\\['time'\\]\\)\\)\\{")
   (notify WebShell))
  (if (bodymask () "NIGGERS\\.NIGGERS") (notify WebShell))
  (if (bodymask () "HTTP flood complete after") (notify WebShell))
  (if (bodymask () "80 \\-b \\$1 \\-i eth0 \\-s 8") (notify WebShell))
  (if (bodymask () exploitcookie) (notify WebShell))
  (if (bodymask () "system\\(\"php \\-f xpl \\$host\"\\)") (notify WebShell))
  (if (bodymask () "sh go \\$1\\.\\$x") (notify WebShell))
  (if (bodymask () az88pix00q98) (notify WebShell))
  (if (bodymask () "unless\\(open\\(PFD,\\$g_upload_db\\)\\)")
   (notify WebShell))
  (if (bodymask () "www\\.t0s\\.org") (notify WebShell))
  (if
   (bodymask ()
    "\\$value \\=~ s/%\\(\\.\\.\\)/pack\\('c',hex\\(\\$1\\)\\)/eg;")
   (notify WebShell))
  (if (bodymask () "The Dark Raver") (notify WebShell))
  (if
   (bodymask ()
    Q3JlZGl0IDogVW5kZXJncm91bmQgRGV2aWwgJm5ic3A7ICB8DQo8YSBocmVmP)
   (notify WebShell))
  (if (bodymask () "\\}elseif\\(\\$_GET\\['page'\\]\\=\\='ddos'")
   (notify WebShell))
  (if (bodymask () "\\{\\$_POST\\['root'\\]\\}") (notify WebShell))
  (if (bodymask () "I/gcZ/vX0A10DDRDg7Ezk/d\\+3\\+8qvqqS1K0\\+AXY")
   (notify WebShell))
  (if
   (bodymask ()
    "FJ3FkuPKFkU/53WEBmIaipktnLwQW8z49dc1rbbLqsw8e69l6vJM\\+3/124xVn\\+7l")
   (notify WebShell))
  (if
   (bodymask ()
    "\\\\u003c\\\\u0069\\\\u006d\\\\u0067\\\\u0020\\\\u0073\\\\u0072\\\\u0063\\\\u003d\\\\u0022\\\\u0068\\\\u0074\\\\u0074\\\\u0070\\\\u003a\\\\u002f\\\\u002f")
   (notify WebShell))
  (if (bodymask () 463839610c000b00800100ffffffffffff21f90401000001002c000)
   (notify WebShell))
  (if (bodymask () "fread\\(\\$fp, filesize\\(\\$fichero\\)\\)")
   (notify WebShell))
  (if (bodymask () "\\$baslik\\=\\$_POST\\['baslik'\\]") (notify WebShell))
  (if (bodymask () "proc_open\\('IHSteam") (notify WebShell))
  (if
   (bodymask ()
    "\\\\x31\\\\xdb\\\\xf7\\\\xe3\\\\x53\\\\x43\\\\x53\\\\x6a\\\\x02\\\\x89\\\\xe1\\\\xb0\\\\x66\\\\xcd")
   (notify WebShell))
  (if
   (bodymask () AAAAAAAAMAAwABAAAAeAUAADQAAADsCQAAAAAAADQAIAADACgAFwAUAAEA)
   (notify WebShell))
  (if (bodymask () "\\$ini\\['users'\\] \\= array\\('root' \\=\\>")
   (notify WebShell))
  (if
   (bodymask () HJ3HjutckoRfpXf9A1zQO2AwDRrRey9uGvTeez79qAao1a0rgudkZkR8Ra)
   (notify WebShell))
  (if
   (bodymask ()
    "curl_setopt\\(\\$ch, CURLOPT_URL, \"http\\://\\$host\\:2082\"\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\<%\\= \"\\\\\" & oScriptNet\\.ComputerName & \"\\\\\" & oScriptNet\\.UserName %\\>")
   (notify WebShell))
  (if
   (bodymask ()
    "sqlCommand\\.Parameters\\.Add\\(\\(\\(TableCell\\)dataGridItem\\.Controls\\[0\\]\\)\\.Text, SqlDbType\\.Decimal\\)\\.Value \\= decimal")
   (notify WebShell))
  (if
   (bodymask ()
    "Response\\.Write\\(\"\\<br\\>\\( \\) \\<a href\\=\\?type\\=1&file\\=\" & server\\.URLencode\\(item\\.path\\) & \"\\\\\\>\" & item")
   (notify WebShell))
  (if
   (bodymask ()
    "new FileStream\\(Path\\.Combine\\(fileInfo\\.DirectoryName, Path\\.GetFileName\\(httpPostedFile\\.FileName\\)\\), FileMode\\.Create")
   (notify WebShell))
  (if
   (bodymask ()
    "Response\\.Write\\(Server\\.HtmlEncode\\(this\\.ExecuteCommand\\(txtCommand\\.Text\\)\\)\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\<%\\=Request\\.Servervariables\\(\"SCRIPT_NAME\"\\)%\\>\\?txtpath\\=\\<%\\=Request\\.QueryString\\(\"txtpath")
   (notify WebShell))
  (if
   (bodymask ()
    "outstr \\+\\= string\\.Format\\(\"\\<a href\\='\\?fdir\\=\\{0\\}'\\>\\{1\\}/\\</a\\>&nbsp;\"")
   (notify WebShell))
  (if
   (bodymask ()
    "QOiKWAgV613LvstKY\\+UB98JZTRGIhYBdHuJCAwm\\+Xth16AwQ8X4tPMcMVZQte")
   (notify WebShell))
  (if (bodymask () "re\\.findall\\(dirt\\+'\\(\\.\\*\\)',prognm\\)\\[0\\]")
   (notify WebShell))
  (if (bodymask () "find / \\-name \\.ssh \\> \\$dir/sshkeys/sshkeys")
   (notify WebShell))
  (if
   (bodymask ()
    "FS_chk_func_libc\\=\\( \\$\\(readelf \\-s \\$FS_libc \\| grep _chk@@ \\| awk")
   (notify WebShell))
  (if (bodymask () Ly83MTg3OWQyMTJkYzhjYmY0ZDRmZDA0NGEzZDE3Zjk3ZmI2N)
   (notify WebShell))
  (if
   (bodymask ()
    "\\$file \\= \\$_FILES\\[\"filename\"\\]\\[\"name\"\\]; echo \"\\<a href\\=\\\\\"\\$file\\\\\"\\>\\$file\\</a\\>\";\\} else \\{echo\\(\"empty\"\\);\\}")
   (notify WebShell))
  (if (bodymask () DJ7VIU7RICXr6sEEV2cBtHDSOe9nVdpEGhEmvRVRNURfw1wQ)
   (notify WebShell))
  (if (bodymask () "Lz8_Ly8vDx8e_v7\\-7u7u3s7uzs7Ozq6unq7erq6uvq5\\-jo6ujn5")
   (notify WebShell))
  (if
   (bodymask ()
    "iVBORw0KGgoAAAANSUhEUgAAAAoAAAAICAYAAADA\\-m62AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQU")
   (notify WebShell))
  (if
   (bodymask ()
    "server\\.\\</p\\>\\\\r\\\\n\\</body\\>\\</html\\>\";exit;\\}if\\(preg_match\\(")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$Fchmod,\\$Fdata,\\$Options,\\$Action,\\$hddall,\\$hddfree,\\$hddproc,\\$uname,\\$idd\\)\\:shared")
   (notify WebShell))
  (if (bodymask () "php \"\\.\\$wso_path") (notify WebShell))
  (if
   (bodymask ()
    "\\$prod\\=\"sy\"\\.\"s\"\\.\"tem\";\\$id\\=\\$prod\\(\\$_REQUEST\\['product'\\]\\);\\$\\{'id'\\};")
   (notify WebShell))
  (if (bodymask () "@assert\\(\\$_REQUEST\\['PHPSESSID'\\]")
   (notify WebShell))
  (if
   (bodymask ()
    "POST \\{\\$path\\}\\{\\$connector\\}\\?Command\\=FileUpload&Type\\=File&CurrentFolder\\=")
   (notify WebShell))
  (if (bodymask () "find / \\-type f \\-name \\.htpasswd") (notify WebShell))
  (if (bodymask () "find / \\-type f \\-perm \\-02000 \\-ls")
   (notify WebShell))
  (if (bodymask () "find / \\-type f \\-perm \\-04000 \\-ls")
   (notify WebShell))
  (if
   (bodymask ()
    "\"admin1\\.php\", \"admin1\\.html\", \"admin2\\.php\", \"admin2\\.html\", \"yonetim\\.php\", \"yonetim\\.html\"")
   (notify WebShell))
  (if
   (bodymask ()
    "@path1\\=\\('admin/','administrator/','moderator/','webadmin/','adminarea/','bb\\-admin/','adminLogin/'")
   (notify WebShell))
  (if
   (bodymask () "cat \\$\\{blklog\\[2\\]\\} \\| grep \"root\\:x\\:0\\:0\"")
   (notify WebShell))
  (if
   (bodymask ()
    "\\?url\\='\\.\\$_SERVER\\['HTTP_HOST'\\]\\)\\.unlink\\(ROOT_DIR\\.")
   (notify WebShell))
  (if
   (bodymask ()
    "long int\\:t\\(0,3\\)\\=r\\(0,3\\);\\-2147483648;2147483647;")
   (notify WebShell))
  (if
   (bodymask ()
    "create_function\\(\"&\\$\"\\.\"function\",\"\\$\"\\.\"function \\= chr\\(ord\\(\\$\"\\.\"function\\)\\-3\\);\"\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "function google_bot\\(\\) \\{\\$sUserAgent \\= strtolower\\(\\$_SERVER\\['HTTP_USER_AGENT'\\]\\);if\\(\\!\\(strp")
   (notify WebShell))
  (if
   (bodymask ()
    "copy\\(\\$_FILES\\['upkk'\\]\\['tmp_name'\\],\"kk/\"\\.basename\\(\\$_FILES\\['upkk'\\]\\['name'\\]\\)\\);")
   (notify WebShell))
  (if
   (bodymask ()
    "for \\(\\$value\\) \\{ s/&/&amp;/g; s/\\</&lt;/g; s/\\>/&gt;/g; s/\"/&quot;/g; \\}")
   (notify WebShell))
  (if (bodymask () "\\$db_d \\= @mysql_select_db\\(\\$database,\\$con1\\);")
   (notify WebShell))
  (if
   (bodymask ()
    "Send this file\\: \\<INPUT NAME\\=\"userfile\" TYPE\\=\"file\"\\>")
   (notify WebShell))
  (if (bodymask () "fwrite \\(\\$fp, \"\\$yazi\"\\);") (notify WebShell))
  (if
   (bodymask ()
    "map \\{ read_shell\\(\\$_\\) \\} \\(\\$sel_shell\\-\\>can_read\\(0\\.01\\)\\);")
   (notify WebShell))
  (if (bodymask () "2\\>&1 1\\>&2\" \\: \" 1\\>&1 2\\>&1\"\\);")
   (notify WebShell))
  (if
   (bodymask ()
    "global \\$mysqlHandle, \\$dbname, \\$tablename, \\$old_name, \\$name,")
   (notify WebShell))
  (if
   (bodymask ()
    "__all__ \\= \\[\"SMTPServer\",\"DebuggingServer\",\"PureProxy\",\"MailmanProxy\"\\]")
   (notify WebShell))
  (if (bodymask () "if \\(is_file\\(\"/tmp/\\$ekinci\"\\)\\)\\{")
   (notify WebShell))
  (if
   (bodymask () "if\\(\\$cmd \\!\\= \"\"\\) print Shell_Exec\\(\\$cmd\\);")
   (notify WebShell))
  (if (bodymask () "\\$cmd \\= \\(\\$_REQUEST\\['cmd'\\]\\);")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$uploadfile \\= \\$rpath\\.\"/\" \\. \\$_FILES\\['userfile'\\]\\['name'\\];")
   (notify WebShell))
  (if (bodymask () "if \\(\\$funcarg \\=~ /\\^portscan \\(\\.\\*\\)/\\)")
   (notify WebShell))
  (if (bodymask () "\\<% For Each Vars In Request\\.ServerVariables %\\>")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\(''\\=\\=\\(\\$df\\=@ini_get\\('disable_functions'\\)\\)\\)\\{echo")
   (notify WebShell))
  (if (bodymask () "\\$filename \\= \\$backupstring\\.\"\\$filename\";")
   (notify WebShell))
  (if
   (bodymask ()
    "\\<%\\#@~\\^HwAAAA\\=\\=@\\#@&DnkwKx/\127R\127UN@\\#@&nx9Pd;\\(@\\#@&ugcAAA\\=\\=\\^\\#~@%\\>")
   (notify WebShell))
  (if (bodymask () "\\$function\\(\\$_POST\\['cmd'\\]\\)") (notify WebShell))
  (if (bodymask () "echo \"FILE UPLOADED TO \\$dez\";") (notify WebShell))
  (if
   (bodymask ()
    "if \\(\\!@is_link\\(\\$file\\) && \\(\\$r \\= realpath\\(\\$file\\)\\) \\!\\= FALSE\\) \\$file \\= \\$r;")
   (notify WebShell))
  (if
   (bodymask ()
    "UNION SELECT '0' , '\\<\\? system\\(\\\\\\$_GET\\[cpc\\]\\);exit; \\?\\>' ,0 ,0 ,0 ,0 INTO OUTFILE '\\$outfile")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\(move_uploaded_file\\(\\$_FILES\\[\"fic\"\\]\\[\"tmp_name\"\\],good_link\\(\"\\./\"\\.\\$_FILES\\[\"fic\"\\]\\[\"name\"\\]\\)\\)\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "connect\\(SOCKET, sockaddr_in\\(\\$ARGV\\[1\\], inet_aton\\(\\$ARGV\\[0\\]\\)\\)\\) or die print")
   (notify WebShell))
  (if
   (bodymask ()
    "elseif\\(@is_writable\\(\\$FN\\) && @is_file\\(\\$FN\\)\\) \\$tmpOutMF")
   (notify WebShell))
  (if
   (bodymask ()
    "while \\(\\$row \\= mysql_fetch_array\\(\\$result,MYSQL_ASSOC\\)\\) print_r\\(\\$row\\);")
   (notify WebShell))
  (if (bodymask () "\\$fe\\(\"\\$cmd  2\\>&1\"\\);") (notify WebShell))
  (if
   (bodymask ()
    "send\\(SOCK5, \\$msg, 0, sockaddr_in\\(\\$porta, \\$iaddr\\)\\) and \\$pacotes\\{o\\}\\+\\+;;")
   (notify WebShell))
  (if
   (bodymask ()
    "\\} elsif \\(\\$servarg \\=~ /\\^\\\\\\:\\(\\.\\+\\?\\)\\\\\\!\\(\\.\\+\\?\\)\\\\@\\(\\.\\+\\?\\) PRIVMSG \\(\\.\\+\\?\\) \\\\\\:\\(\\.\\+\\)/\\) \\{")
   (notify WebShell))
  (if (bodymask () "elseif\\(function_exists\\(\"shell_exec\"\\)\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "system\\(\"\\$cmd 1\\> /tmp/cmdtemp 2\\>&1; cat /tmp/cmdtemp; rm /tmp/cmdtemp\"\\);")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$_FILES\\['probe'\\]\\['size'\\], \\$_FILES\\['probe'\\]\\['type'\\]\\);")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$ra44  \\= rand\\(1,99999\\);\\$sj98 \\= \"sh\\-\\$ra44\";\\$ml \\= \"\\$sd98\";\\$a5 \\= \\$_SERVER\\['HTTP_REFERER'\\];")
   (notify WebShell))
  (if
   (bodymask ()
    "mysql_query\\(\"CREATE TABLE `xploit` \\(`xploit` LONGBLOB NOT NULL\\)\"\\);")
   (notify WebShell))
  (if
   (bodymask ()
    "passthru\\( \\$bindir\\.\"mysqldump \\-\\-user\\=\\$USERNAME \\-\\-password\\=\\$PASSWORD")
   (notify WebShell))
  (if
   (bodymask ()
    "\\<a href\\='\\$PHP_SELF\\?action\\=viewSchema&dbname\\=\\$dbname&tablename\\=\\$tablename'\\>Schema\\</a\\>")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\(get_magic_quotes_gpc\\(\\)\\)\\$shellOut\\=stripslashes\\(\\$shellOut\\);")
   (notify WebShell))
  (if
   (bodymask ()
    "if \\(\\!defined\\$param\\{cmd\\}\\)\\{\\$param\\{cmd\\}\\=\"ls \\-la\"\\};")
   (notify WebShell))
  (if (bodymask () "shell_exec\\('uname \\-a'\\);") (notify WebShell))
  (if
   (bodymask ()
    "if \\(move_uploaded_file\\(\\$_FILES\\['fila'\\]\\['tmp_name'\\], \\$curdir\\.\"/\"\\.\\$_FILES\\['fila'\\]\\['name'\\]\\)\\) \\{")
   (notify WebShell))
  (if
   (bodymask ()
    "if \\(empty\\(\\$_POST\\['wser'\\]\\)\\) \\{\\$wser \\= \"whois\\.ripe\\.net\";\\} else \\$wser \\= \\$_POST\\['wser'\\];")
   (notify WebShell))
  (if (bodymask () "\\<%\\=env\\.queryHashtable\\(\"user\\.name\"\\)%\\>")
   (notify WebShell))
  (if
   (bodymask ()
    "PySystemState\\.initialize\\(System\\.getProperties\\(\\), null, argv\\);")
   (notify WebShell))
  (if (bodymask () "if\\(\\!\\$whoami\\)\\$whoami\\=exec\\(\"whoami\"\\);")
   (notify WebShell))
  (if (bodymask () "shell_exec\\(\\$_POST\\['cmd'\\] \\. \" 2\\>&1\"\\);")
   (notify WebShell))
  (if
   (bodymask ()
    "PnVlkWM63\\!@\\#@&dKx~nMDWM~D\127/Esn~x\1276D@\\#@&P~~,\\?nY,WP\\{Poj")
   (notify WebShell))
  (if (bodymask () "\\!\\$_REQUEST\\[\"c99sh_surl\"\\]\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\(ereg\\('\\^\\[\\[\\:blank\\:\\]\\]\\*cd\\[\\[\\:blank\\:\\]\\]\\*\\$', \\$_REQUEST\\['command'\\]\\)\\)")
   (notify WebShell))
  (if (bodymask () "\\$login\\=@posix_getuid\\(\\);") (notify WebShell))
  (if (bodymask () "system\\(\"unset HISTFILE; unset SAVEHIST")
   (notify WebShell))
  (if (bodymask () "\\<HTML\\>\\<HEAD\\>\\<TITLE\\>cgi\\-shell\\.py")
   (notify WebShell))
  (if (bodymask () "execl\\(\"/bin/sh\",\"sh\",\"\\-i\",\\(char\\*\\)0\\);")
   (notify WebShell))
  (if (bodymask () "ncftpput \\-u \\$ftp_user_name") (notify WebShell))
  (if (bodymask () "\\$a\\[hits\\]'\\); \\\\r\\\\n\\#endquery\\\\r\\\\n")
   (notify WebShell))
  (if (bodymask () "\\{\\$\\{passthru\\(\\$cmd\\)\\}\\}\\<br\\>")
   (notify WebShell))
  (if
   (bodymask () "\\$backdoor\\-\\>ccopy\\(\\$cfichier,\\$cdestination\\);")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$izinler2\\=substr\\(base_convert\\(@fileperms\\(\\$fname\\),10,8\\),\\-4\\);")
   (notify WebShell))
  (if
   (bodymask ()
    "for\\(;\\$paddr\\=accept\\(CLIENT, SERVER\\);close CLIENT\\) \\{")
   (notify WebShell))
  (if (bodymask () Asmodeus) (notify WebShell))
  (if (bodymask () "passthru\\(getenv\\(\"HTTP_ACCEPT_LANGUAGE")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$____\\=@gzinflate\\(\\$____\\)\\)\\{if\\(isset\\(\\$_POS")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$subj\\=urldecode\\(\\$_GET\\['su'\\]\\);\\$body\\=urldecode\\(\\$_GET\\['bo'\\]\\);\\$sds\\=urldecode\\(\\$_GET\\['sd'\\]\\)")
   (notify WebShell))
  (if (bodymask () "\\$ka\\='\\<\\?//BRE';\\$kaka\\=\\$ka\\.'ACK//\\?\\>")
   (notify WebShell))
  (if (bodymask () "Cautam fisierele de configurare") (notify WebShell))
  (if (bodymask () BRUTEFORCING) (notify WebShell))
  (if (bodymask () "pwd \\> Generasi\\.dir") (notify WebShell))
  (if
   (bodymask ()
    "xh \\-s \"/usr/local/apache/sbin/httpd \\-DSSL\" \\./httpd \\-m \\$1")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$a\\=\\(substr\\(urlencode\\(print_r\\(array\\(\\),1\\)\\),5,1\\)\\.c\\)")
   (notify WebShell))
  (if (bodymask () "\\!@\\$_COOKIE\\[\\$sessdt_k\\]") (notify WebShell))
  (if
   (bodymask ()
    "SELECT 1 FROM mysql\\.user WHERE concat\\(`user`, '@', `host`\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "copy\\(\\$_FILES\\[x\\]\\[tmp_name\\],\\$_FILES\\[x\\]\\[name\\]\\)\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$MessageSubject \\= base64_decode\\(\\$_POST\\[\"msgsubject\"\\]\\);")
   (notify WebShell))
  (if (bodymask () "rename\\(\"wso\\.php\",") (notify WebShell))
  (if
   (bodymask ()
    "\\$redirectURL\\='http\\://'\\.\\$rSite\\.\\$_SERVER\\['REQUEST_URI'\\];if\\(isset\\(\\$_SERVER\\['HTTP_REFERER'\\]\\)")
   (notify WebShell))
  (if (bodymask () "\\$filepath\\=@realpath\\(\\$_POST\\['filepath'\\]\\);")
   (notify WebShell))
  (if (bodymask () "Worker_GetReplyCode\\(\\$opData\\['recvBuffer'\\]\\)")
   (notify WebShell))
  (if (bodymask () "FaTaLisTiCz_Fx Fx29Sh") (notify WebShell))
  (if (bodymask () "w4ck1ng shell") (notify WebShell))
  (if (bodymask () "private Shell by m4rco") (notify WebShell))
  (if (bodymask () "Shell by Mawar_Hitam") (notify WebShell))
  (if (bodymask () "PHPSHELL\\.PHP") (notify WebShell))
  (if
   (bodymask ()
    "round\\(0\\+9830\\.4\\+9830\\.4\\+9830\\.4\\+9830\\.4\\+9830\\.4\\)\\)\\=\\=")
   (notify WebShell))
  (if
   (bodymask ()
    "vzv6d\\+iOvtkd38TlHu8mQavXdnJCbpQcpXhNbbLmZOqMopDZeNalb\\+VKledhCjpVAMQSQnxVIECQAfLu5KgLmwB6ehQQGNSBYjpg9g5GdBihXo")
   (notify WebShell))
  (if
   (bodymask ()
    "if \\(ereg\\('\\^\\[\\[\\:blank\\:\\]\\]\\*cd\\[\\[\\:blank\\:\\]\\]\\+\\(\\[\\^;\\]\\+\\)\\$', \\$command, \\$regs\\)\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "LS0gRHVtcDNkIGJ5IFBpcnVsaW4uUEhQIFdlYnNoM2xsIHYxLjAgYzBkZWQgYnkgcjBkcjEgOkw\\=")
   (notify WebShell))
  (if
   (bodymask ()
    5jb20iKW9yIHN0cmlzdHIoJHJlZmVyZXIsImFwb3J0Iikgb3Igc3RyaXN0cigkcmVmZXJlciwibmlnbWEiKSBvciBzdHJpc3RyKCRyZWZlcmVyLCJ3ZWJhbHRhIikgb3Igc3RyaXN0cigk)
   (notify WebShell))
  (if (bodymask () "eval\\(base64_decode\\(\\$_") (notify WebShell))
  (if
   (bodymask ()
    "wsoEx\\('tar cfzv ' \\. escapeshellarg\\(\\$_POST\\['p2'\\]\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\<nobr\\>\\<b\\>\\$cdir\\$cfile\\</b\\> \\(\"\\.\\$file\\[\"size_str\"\\]\\.\"\\)\\</nobr\\>\\</td\\>\\</tr\\>\\<form name\\=curr_file\\>")
   (notify WebShell))
  (if (bodymask () "Content\\-Type\\: \\$_") (notify WebShell))
  (if
   (bodymask ()
    "\\</td\\>\\<td id\\=fa\\>\\[ \\<a title\\=\\\\\"Home\\: '\"\\.htmlspecialchars\\(str_replace\\(\"\\\\\", \\$sep, getcwd\\(\\)\\)\\)\\.\"'\\.\\\\\" id\\=fa href\\=\\\\\"javascript\\:ViewDir\\('\"\\.rawurlencode")
   (notify WebShell))
  (if
   (bodymask ()
    "CQboGl7f\\+xcAyUysxb5mKS6kAWsnRLdS\\+sKgGoZWdswLFJZV8tVzXsq\\+meSPHMxTI3nSUB4fJ2vR3r3OnvXtNAqN6wn/DtTTi\\+Cu1UOJwNL")
   (notify WebShell))
  (if (bodymask () "WSOsetcookie\\(md5\\(\\$_SERVER\\['HTTP_HOST'\\]\\)")
   (notify WebShell))
  (if
   (bodymask ()
    X1NFU1NJT05bJ3R4dGF1dGhpbiddID0gdHJ1ZTsNCiAgICBpZiAoJF9QT1NUWydybSddKSB7DQogICAgICBzZXRjb29raWUoJ3R4dGF1dGhfJy4kcm1ncm91cCwgbW)
   (notify WebShell))
  (if (bodymask () "J@\\!Vr@\\*&RHRw~JLw\\.G\\|xlhnLJ~\\?1\\.bwObxbP\\|\\!V")
   (notify WebShell))
  (if (bodymask () zehirhacker) (notify WebShell))
  (if
   (bodymask ()
    "\\('\"','&quot;',\\$fn\\)\\)\\.'\";document\\.list\\.submit\\(\\);\\\\'\\>'\\.htmlspecialchars\\(strlen\\(\\$fn\\)\\>format\\?substr\\(\\$fn,0,format\\-3\\)\\.'\\.\\.\\.'\\:\\$fn\\)\\.'\\</a\\>'\\.str_repeat\\(' ',format\\-strlen\\(\\$fn\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "print\\(\\(is_readable\\(\\$f\\) && is_writeable\\(\\$f\\)\\)\\?\"\\<tr\\>\\<td\\>\"\\.w\\(1\\)\\.b\\(\"R\"\\.w\\(1\\)\\.font\\('red','RW',3\\)\\)\\.w\\(1\\)\\:\\(\\(\\(is_readable\\(\\$f\\)\\)\\?\"\\<tr\\>\\<td\\>\"\\.w\\(1\\)\\.b\\(\"R\"\\)\\.w\\(4\\)\\:\"\"\\)\\.\\(\\(is_writabl")
   (notify WebShell))
  (if
   (bodymask ()
    R0lGODlhFAAUAKIAAAAAAP///93d3cDAwIaGhgQEBP///wAAACH5BAEAAAYALAAAAAAUABQAA)
   (notify WebShell))
  (if
   (bodymask ()
    "\\<%\\=Request\\.ServerVariables\\(\"script_name\"\\)%\\>\\?FolderPath\\=\\<%\\=Server\\.URLPathEncode\\(Folder\\.Driv")
   (notify WebShell))
  (if
   (bodymask ()
    m91dCwgJGVvdXQpOw0Kc2VsZWN0KCRyb3V0ID0gJHJpbiwgdW5kZWYsICRlb3V0ID0gJHJpbiwgMTIwKTsNCmlmICghJHJvdXQgICYmICAhJGVvdX)
   (notify WebShell))
  (if (bodymask () "RootShell\\!'\\);self\\.location\\.href\\='http\\:")
   (notify WebShell))
  (if
   (bodymask ()
    "a href\\=\"\\<\\?echo \"\\$fistik\\.php\\?dizin\\=\\$dizin/\\.\\./\"\\?\\>\" style\\=\"text\\-decoration\\: non")
   (notify WebShell))
  (if
   (bodymask ()
    CB2aTZpIDEwMjQtDQojLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KI3JlcXVp)
   (notify WebShell))
  (if
   (bodymask ()
    "s\\(\\)\\.g\\(\\)\\.s\\(\\)\\.s\\(\\)\\.g\\(\\)\\.s\\(\\)\\.s\\(\\)\\.g\\(\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "nt\\)\\(disk_total_space\\(getcwd\\(\\)\\)/\\(1024\\*1024\\)\\) \\. \"Mb \" \\. \"Free space \" \\. \\(int\\)\\(disk_free_space\\(getcwd\\(\\)\\)/\\(1024\\*1024\\)\\) \\. \"Mb \\<")
   (notify WebShell))
  (if (bodymask () "klasvayv\\.asp\\?yenidosya\\=\\<%\\=aktifklas%\\>")
   (notify WebShell))
  (if
   (bodymask ()
    "WT\\+P\\{~EW0ErPOtnU@\\#@&\\^l\\^sP1ldny@\\#@&nsk\\+r0,GT\\+")
   (notify WebShell))
  (if
   (bodymask ()
    "mpty\\(\\$_POST\\['ur'\\]\\)\\) \\$mode \\|\\= 0400; if \\(\\!empty\\(\\$_POST\\['uw'\\]\\)\\) \\$mode \\|\\= 0200; if \\(\\!empty\\(\\$_POST\\['ux'\\]\\)\\) \\$mode \\|\\= 0100")
   (notify WebShell))
  (if
   (bodymask ()
    "/0tVSG/Suv0Ur/haUYAdn3jMQwbbocGffAeC29BN9tmBiJdV1lk\\+jYDU92C94jdtDif\\+xOYjG6CLhx31Uo9x9/eAWgsBK60kK2mLwqzqd")
   (notify WebShell))
  (if
   (bodymask ()
    "crlf\\.'unlink\\(\\$name\\);'\\.\\$crlf\\.'rename\\(\"~\"\\.\\$name, \\$name\\);'\\.\\$crlf\\.'unlink\\(\"grp_repair\\.php\"")
   (notify WebShell))
  (if (bodymask () DX_Header_drawn) (notify WebShell))
  (if (bodymask () "\\[Av4bfCYCS,xKWk\\$\\+TkUS,xnGdAx\\[O")
   (notify WebShell))
  (if
   (bodymask ()
    BDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAQABADASIAAhEBA)
   (notify WebShell))
  (if (bodymask () "ctshell\\.php") (notify WebShell))
  (if
   (bodymask ()
    "Executed command\\: \\<b\\>\\<font color\\=\\#dcdcdc\\>\\[\\$cmd\\]")
   (notify WebShell))
  (if (bodymask () "WSCRIPT\\.SHELL") (notify WebShell))
  (if (bodymask () casus15) (notify WebShell))
  (if
   (bodymask ()
    "R0lGODlhJgAWAIAAAAAAAP///yH5BAUUAAEALAAAAAAmABYAAAIvjI\\+py\\+0PF4i0gVvzuVxXDnoQ")
   (notify WebShell))
  (if (bodymask () "admin@spygrup\\.org") (notify WebShell))
  (if (bodymask () temp_r57_table) (notify WebShell))
  (if (bodymask () "\\$c99sh_updatefurl") (notify WebShell))
  (if (bodymask () "By Psych0") (notify WebShell))
  (if (bodymask () c99ftpbrutecheck) (notify WebShell))
  (if
   (bodymask ()
    "\\<textarea name\\=\\\\\"phpev\\\\\" rows\\=\\\\\"5\\\\\" cols\\=\\\\\"150\\\\\"\\>\"\\.@\\$_POST\\['phpev'\\]\\.\"\\</textarea\\>\\<br\\>")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$info \\.\\= \\(\\(\\$perms & 0x0040\\) \\?\\(\\(\\$perms & 0x0800\\) \\? 's' \\: 'x' \\) \\:\\(\\(\\$perms & 0x0800\\) \\? 'S' \\: '\\-'\\)")
   (notify WebShell))
  (if (bodymask () "\\$rand_writable_folder_fullpath") (notify WebShell))
  (if (bodymask () "Dr\\.abolalh") (notify WebShell))
  (if (bodymask () "K\\!LL3r") (notify WebShell))
  (if (bodymask () MrHazem) (notify WebShell))
  (if (bodymask () "C0derz\\.com") (notify WebShell))
  (if (bodymask () "OLB\\:PRODUCT\\:ONLINE_BANKING") (notify WebShell))
  (if (bodymask () "BY MMNBOBZ") (notify WebShell))
  (if (bodymask () ConnectBackShell) (notify WebShell))
  (if (bodymask () Hackeado) (notify WebShell))
  (if (bodymask () d3b~X) (notify WebShell))
  (if (bodymask () rahui) (notify WebShell))
  (if (bodymask () "Mr\\.HiTman") (notify WebShell))
  (if (bodymask () "Mrlool\\.exe") (notify WebShell))
  (if
   (bodymask ()
    "function\\s+read_pic\\(\\s*\\$A\\s*\\)\\s*{\\s*\\$a\\s*=\\s*\\$_SERVER")
   (notify WebShell))
  (if
   (bodymask ()
    "filemtime\\(\\$basepath\\s*\\.\\s*['\"]/configuration\\.php")
   (notify WebShell))
  (if
   (bodymask ()
    "list\\s*\\(\\s*\\$host\\s*,\\s*\\$port\\s*,\\s*\\$size\\s*,\\s*\\$exec_time")
   (notify WebShell))
  (if (bodymask () "listing_page\\(\\s*notice\\(\\s*['\"]symlinked")
   (notify WebShell))
  (if (bodymask () "make_dir_and_file\\(\\s*\\$path_joomla")
   (notify WebShell))
  (if (bodymask () "function\\s+inDiapason") (notify WebShell))
  (if (bodymask () "&&\\s*!empty\\(\\s*\\$_COOKIE\\[['\"]fill['\"]\\]")
   (notify WebShell))
  (if (bodymask () "file_exists\\s*\\(*\\s*['\"]/var/tmp/")
   (notify WebShell))
  (if
   (bodymask ()
    "str_replace\\(\\$find\\s*,\\s*\\$find\\s*\\.\\s*\\$html\\s*,\\s*\\$text")
   (notify WebShell))
  (if (bodymask () "\\$datamasii=date\\(\"D M d, Y g:i a\"\\)")
   (notify WebShell))
  (if (bodymask () "\\$adddate=date\\(\"D M d, Y g:i a\"\\)")
   (notify WebShell))
  (if (bodymask () "fuck\\s+your\\s+mama") (notify WebShell))
  (if (bodymask () "Googlebot['\"]{0,1}\\s*\\)\\){echo\\s+file_get_contents")
   (notify WebShell))
  (if (bodymask () "['\"]{0,1}.c.['\"]{0,1}\\.substr\\(\\$vbg,")
   (notify WebShell))
  (if (bodymask () "array\\(\\$en,\\$es,\\$ef,\\$el\\)") (notify WebShell))
  (if (bodymask () "loc\\s*=\\s*['\"]{0,1}<\\?echo\\s+\\$redirect;\\s*\\?>")
   (notify WebShell))
  (if (bodymask () "Kazan/index\\.html") (notify WebShell))
  (if (bodymask () "==0\\){jsonQuit\\(\\$") (notify WebShell))
  (if (bodymask () "@stream_socket_client\\(['\"]{0,1}tcp://\\$")
   (notify WebShell))
  (if (bodymask () "::['\"]\\.phpversion\\(\\)\\.['\"]::") (notify WebShell))
  (if (bodymask () "preg_replace\\(['\"].UTF\\\\-8:\\(.\\*\\).Use")
   (notify WebShell))
  (if (bodymask () "\"=>\\${\\${\"\\\\x") (notify WebShell))
  (if (bodymask () "fsockopen\\(\\$m\\[0\\],\\$m\\[10\\],\\$_,\\$__,\\$m")
   (notify WebShell))
  (if (bodymask () "eVaL\\(\\s*trim\\(\\s*baSe64_deCoDe\\(")
   (notify WebShell))
  (if (bodymask () "echo\\s*md5\\(\\$_POST\\[['\"]{0,1}check['\"]{0,1}\\]")
   (notify WebShell))
  (if (bodymask () "img src=['\"]opera000\\.png") (notify WebShell))
  (if (bodymask () "function reload\\(\\){header\\(\"Location")
   (notify WebShell))
  (if (bodymask () "substr_count\\(getenv\\(\\\\['\"]HTTP_REFERER")
   (notify WebShell))
  (if (bodymask () "webi\\.ru/webi_files/php_libmail") (notify WebShell))
  (if
   (bodymask ()
    "chr2=\\(\\(enc2&15\\)<<4\\)\\|\\(enc3>>2\\);chr3=\\(\\(enc3&3\\)<<6\\)\\|enc4")
   (notify WebShell))
  (if (bodymask () REREFER_PTTH) (notify WebShell))
  (if (bodymask () tsoh_ptth) (notify WebShell))
  (if (bodymask () tnega_resu_ptth) (notify WebShell))
  (if (bodymask () "mmcrypt\\(\\$data, \\$key, \\$iv, \\$decrypt = FALSE")
   (notify WebShell))
  (if (bodymask () "fopo\\.com\\.ar") (notify WebShell))
  (if (bodymask () spravochnik-nomerov-) (notify WebShell))
  (if (bodymask () icq-dlya-telefona-) (notify WebShell))
  (if (bodymask () telefonnaya-baza-) (notify WebShell))
  (if (bodymask () "slesh\\+slesh\\+domen\\+point") (notify WebShell))
  (if (bodymask () "src=\"files_site/js\\.js") (notify WebShell))
  (if
   (bodymask ()
    "\\$t=\\$s;\\s*\\$o\\s*=\\s*['\"]['\"];\\s*for\\(\\$i=0;\\$i<strlen\\(\\$t\\);\\$i\\+\\+\\){\\s*\\$o\\s*\\.=\\s*\\$t{\\$i}")
   (notify WebShell))
  (if
   (bodymask ()
    "WBS_DIR\\s*\\.\\s*['\"]{0,1}temp/['\"]{0,1}\\s*\\.\\s*\\$activeFile\\s*\\.\\s*['\"]{0,1}\\.tmp")
   (notify WebShell))
  (if (bodymask () "@*mail\\(\\$mosConfig_mailfrom, \\$mosConfig_live_site")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$[a-zA-Z0-9_]+?/\\*.{1,10}\\*/\\s*\\.\\s*\\$[a-zA-Z0-9_]+?/\\*.{1,10}\\*/")
   (notify WebShell))
  (if (bodymask () "@\\$_POST\\[\\(chr\\(") (notify WebShell))
  (if (bodymask () "<\\?php\\s+rename\\(['\"]wso\\.php['\"]")
   (notify WebShell))
  (if
   (bodymask () "\\$str=['\"]{0,1}<h1>403\\s+Forbidden</h1><!--\\s*token:")
   (notify WebShell))
  (if
   (bodymask () "chunk_split\\(base64_encode\\(fread\\(\\${\\${['\"]{0,1}")
   (notify WebShell))
  (if
   (bodymask ()
    "ini_get\\(['\"]{0,1}filter\\.default_flags['\"]{0,1}\\)\\){foreach")
   (notify WebShell))
  (if (bodymask () "file_get_contents\\(trim\\(\\$f\\[\\$_GET\\[")
   (notify WebShell))
  (if
   (bodymask ()
    "mail\\(\\$arr\\[['\"]{0,1}to['\"]{0,1}\\],\\$arr\\[['\"]{0,1}subj['\"]{0,1}\\],\\$arr\\[['\"]{0,1}msg['\"]{0,1}\\],\\$arr\\[['\"]{0,1}head['\"]{0,1}\\]\\);")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\(isset\\(\\$_POST\\[['\"]{0,1}msgsubject['\"]{0,1}\\]\\)\\)")
   (notify WebShell))
  (if (bodymask () "base64_decode\\(\\$_POST\\[['\"]{0,1}_-")
   (notify WebShell))
  (if
   (bodymask () "register_shutdown_function\\(\\s*['\"]{0,1}read_ans_code")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$param\\s*=\\s*\\$param\\s*x\\s*\\$n\\.substr\\s*\\(\\$param\\s*,\\s*length\\(\\$param\\)")
   (notify WebShell))
  (if (bodymask () "base['\"]{0,1}\\.\\(32\\*2\\)") (notify WebShell))
  (if
   (bodymask ()
    "if\\(@\\$vars\\(get_magic_quotes_gpc\\(\\)\\s*\\?\\s*stripslashes\\(\\$uri\\)")
   (notify WebShell))
  (if (bodymask () "\\)\\];}if\\(isset\\(\\$_SERVER\\[_") (notify WebShell))
  (if (bodymask () "if\\(empty\\(\\$_COOKIE\\[['\"]x['\"]\\]\\)\\){echo")
   (notify WebShell))
  (if
   (bodymask () "is_writable\\(\\$dir\\.['\"]wp-includes/version\\.php['\"]")
   (notify WebShell))
  (if (bodymask () "Apple\\s+SpAm\\s+ReZulT") (notify WebShell))
  (if (bodymask () "\\#\\s*stealth\\s*bot") (notify WebShell))
  (if (bodymask () "\\#\\s*securityspace\\.com") (notify WebShell))
  (if (bodymask () "URL=<\\?echo\\s+\\$index;\\s+\\?>") (notify WebShell))
  (if
   (bodymask ()
    "<script\\s+type=['\"]{0,1}text/javascript['\"]{0,1}\\s+src=['\"]{0,1}jquery-u\\.js['\"]{0,1}></script>")
   (notify WebShell))
  (if
   (bodymask ()
    "create_function\\(['\"]['\"],\\s*\\$opt\\[1\\]\\s*\\.\\s*\\$opt\\[4\\]")
   (notify WebShell))
  (if
   (bodymask () "file_put_contents\\(SVC_SELF\\s*\\.\\s*['\"]/\\.htaccess")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$allemails\\s*=\\s*@split\\(\"\\\\n\"\\s*,\\s*\\$emaillist\\)")
   (notify WebShell))
  (if (bodymask () Joomla_brute_Force) (notify WebShell))
  (if (bodymask () "\\$sys_params\\s*=\\s*@*file_get_contents")
   (notify WebShell))
  (if (bodymask () "fwrite\\s*\\(\\s*\\$flw\\s*,\\s*\\$fl\\s*\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "file_put_contents\\s*\\(['\"]{0,1}1\\.txt['\"]{0,1}\\s*,\\s*print_r\\s*\\(\\s*\\$_POST\\s*,\\s*true")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$headers\\s*=\\s*\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\[['\"]{0,1}headers['\"]{0,1}\\]")
   (notify WebShell))
  (if (bodymask () "create_function\\s*\\(['\"]['\"]\\s*,\\s*str_rot13")
   (notify WebShell))
  (if (bodymask () "die\\s*\\(\\s*PHP_OS\\s*\\.\\s*chr\\s*\\(")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\s*\\(md5\\(trim\\(\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\[")
   (notify WebShell))
  (if
   (bodymask ()
    "f\\s*=\\s*\\$q\\s*\\.\\s*\\$a\\s*\\.\\s*\\$b\\s*\\.\\s*\\$x")
   (notify WebShell))
  (if (bodymask () "content=['\"]{0,1}1;URL=cgi-bin\\.html\\?cmd")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$url['\"]{0,1}\\s*\\.\\s*\\$session_id\\s*\\.\\s*['\"]{0,1}/login\\.html")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$_SESSION\\[['\"]{0,1}session_pin['\"]{0,1}\\]\\s*=\\s*['\"]{0,1}\\$PIN")
   (notify WebShell))
  (if (bodymask () "fsockopen\\s*\\(\\s*\\$ConnectAddress\\s*,\\s*25")
   (notify WebShell))
  (if (bodymask () "echo\\s+\\$ifupload=['\"]{0,1}\\s*ItsOk\\s*['\"]{0,1}")
   (notify WebShell))
  (if
   (bodymask ()
    "preg_match\\(['\"]/\\(yandex\\|google\\|bot\\)/i['\"],\\s*getenv\\(['\"]HTTP_USER_AGENT")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$mailer\\s*=\\s*\\$_POST\\[['\"]{0,1}x_mailer['\"]{0,1}\\]")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$OOO0O0O00=__FILE__;\\s*\\$OO00O0000\\s*=\\s*0x1b540;\\s*eval")
   (notify WebShell))
  (if (bodymask () "By\\s+WebRooT") (notify WebShell))
  (if
   (bodymask ()
    "header\\(['\"]{0,1}s:\\s*['\"]{0,1}\\s*\\.\\s*php_uname\\s*\\(\\s*['\"]{0,1}n['\"]{0,1}\\s*\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "move_uploaded_file\\(\\$_FILES\\[['\"]{0,1}elif['\"]{0,1}\\]\\[['\"]{0,1}tmp_name")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$gzip\\s*=\\s*@*gzinflate\\s*\\(\\s*@*substr\\s*\\(\\s*\\$gzencode_arg")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\s*\\(\\s*mail\\s*\\(\\s*\\$mails\\[\\$i\\]\\s*,\\s*\\$tema\\s*,\\s*base64_encode\\s*\\(\\s*\\$text")
   (notify WebShell))
  (if
   (bodymask ()
    "fwrite\\s*\\(\\s*\\$fh\\s*,\\s*stripslashes\\s*\\(\\s*@*\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\[")
   (notify WebShell))
  (if
   (bodymask ()
    "echo\\s+file_get_contents\\s*\\(\\s*base64_url_decode\\s*\\(\\s*@*\\$_(GET|POST|SERVER|COOKIE|REQUEST)")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\s*\\(\\s*@*md5\\s*\\(\\s*\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\[")
   (notify WebShell))
  (if
   (bodymask ()
    "chr\\s*\\(\\s*101\\s*\\)\\s*\\.\\s*chr\\s*\\(\\s*118\\s*\\)\\s*\\.\\s*chr\\s*\\(\\s*97\\s*\\)\\s*\\.\\s*chr\\s*\\(\\s*108\\s*\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\[['\"]{0,1}[a-zA-Z0-9_]+?['\"]{0,1}\\]\\(\\s*\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\[['\"]{0,1}[a-zA-Z0-9_]+?['\"]{0,1}\\]\\s*\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$resultFUL\\s*=\\s*stripcslashes\\s*\\(\\s*\\$_POST\\[['\"]{0,1}resultFUL['\"]{0,1}")
   (notify WebShell))
  (if (bodymask () /usr/sbin/httpd) (notify WebShell))
  (if (bodymask () "PRIVMSG\\.\\*:\\.owner\\\\s\\+\\(\\.\\*\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "print\\s+\\$sock\\s+['\"]{0,1}NICK ['\"]{0,1}\\s+\\.\\s+\\$nick\\s+\\.\\s+['\"]{0,1}\\\\n['\"]{0,1}")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$url\\s*=\\s*\\$url\\s*\\.\\s*['\"]{0,1}\\?['\"]{0,1}\\s*\\.\\s*http_build_query\\(\\$query\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "preg_match_all\\(['\"]{0,1}/<a href=\"\\\\/url\\\\\\?q=\\(\\.\\+\\?\\)\\[&\\|\"\\]\\+/is['\"]{0,1}, \\$page\\[['\"]{0,1}exe['\"]{0,1}\\], \\$links\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "<script\\s+language=['\"]{0,1}JavaScript['\"]{0,1}>\\s*parent\\.window\\.opener\\.location\\s*=\\s*['\"]http://")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$p\\s*=\\s*strpos\\s*\\(\\s*\\$tx\\s*,\\s*['\"]{0,1}{\\#['\"]{0,1}\\s*,\\s*\\$p2\\s*\\+\\s*2\\)")
   (notify WebShell))
  (if (bodymask () "\\(msie\\|opera\\)") (notify WebShell))
  (if (bodymask () "RewriteCond\\s*%{HTTP_USER_AGENT}\\s*\\.\\*ndroid\\.\\*")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\s*\\(\\s*is_dir\\s*\\(\\s*\\$FullPath\\s*\\)\\s*\\)\\s*AllDir\\s*\\(\\s*\\$FullPath\\s*,\\s*\\$Files\\s*\\);\\s*}\\s*}")
   (notify WebShell))
  (if
   (bodymask ()
    "['\"]{0,1}From:\\s*['\"]{0,1}\\.\\$_POST\\[['\"]{0,1}realname['\"]{0,1}\\]\\.['\"]{0,1} ['\"]{0,1}\\.['\"]{0,1} <['\"]{0,1}\\.\\$_POST\\[['\"]{0,1}from['\"]{0,1}\\]\\.['\"]{0,1}>\\\\n['\"]{0,1}")
   (notify WebShell))
  (if
   (bodymask ()
    "<!--\\#exec\\s+cmd=['\"]{0,1}\\$HTTP_ACCEPT['\"]{0,1}\\s*-->")
   (notify WebShell))
  (if (bodymask () "\\[-\\]\\s+Connection\\s+faild") (notify WebShell))
  (if
   (bodymask ()
    "if\\(/\\^\\\\:\\$owner!\\.\\*\\\\@\\.\\*PRIVMSG\\.\\*:\\.msgflood\\(\\.\\*\\)/\\){")
   (notify WebShell))
  (if (bodymask () "print\\s*\\$sock \"PRIVMSG \"\\.\\$owner")
   (notify WebShell))
  (if
   (bodymask ()
    "\\]=['\"]{0,1}ip['\"]{0,1}\\s*;\\s*if\\s*\\(\\s*isset\\s*\\(\\s*\\$_SERVER\\[")
   (notify WebShell))
  (if
   (bodymask ()
    "\\]\\s*}\\s*=\\s*trim\\s*\\(\\s*array_pop\\s*\\(\\s*\\${\\s*\\${")
   (notify WebShell))
  (if (bodymask () "print\\(\"\\#\\s+info\\s+OK\\\\n\\\\n\"\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$user_agent\\s*=\\s*preg_replace\\s*\\(\\s*['\"]\\|User\\\\\\.Agent\\\\:\\[\\\\s \\]\\?\\|i['\"]\\s*,\\s*['\"]['\"]\\s*,\\s*\\$user_agent")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$p\\s*=\\s*strpos\\(\\$tx\\s*,\\s*['\"]{0,1}{\\#['\"]{0,1}\\s*,\\s*\\$p2\\s*\\+\\s*2\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "create_function\\s*\\(\\s*['\"]\\$m['\"]\\s*,\\s*['\"]if\\s*\\(\\s*\\$m\\s*\\[\\s*0x01\\s*\\]\\s*==\\s*['\"]L['\"]")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$letter\\s*=\\s*str_replace\\s*\\(\\s*\\$ARRAY\\[0\\]\\[\\$j\\]\\s*,\\s*\\$arr\\[\\$ind\\]\\s*,\\s*\\$letter")
   (notify WebShell))
  (if (bodymask () "IrIsT\\.Ir") (notify WebShell))
  (if (bodymask () "if\\s*\\(detect_mobile_device\\(\\)\\)\\s*{\\s*header")
   (notify WebShell))
  (if (bodymask () "\\$post\\s*=\\s*['\"]\\\\x77\\\\x67\\\\x65")
   (notify WebShell))
  (if (bodymask () "echo\\s*['\"]answer=error['\"]") (notify WebShell))
  (if (bodymask () "url=<\\?php\\s*echo\\s*\\$rand_url;\\?>")
   (notify WebShell))
  (if (bodymask () "if\\(CheckIPOperator\\(\\)\\s*&&\\s*!isModem\\(\\)\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "strpos\\(\\$ua,\\s*['\"]{0,1}yandexbot['\"]{0,1}\\)\\s*!==\\s*false")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\s*\\(\\$key\\s*!=\\s*['\"]{0,1}mail_to['\"]{0,1}\\s*&&\\s*\\$key\\s*!=\\s*['\"]{0,1}smtp_server['\"]{0,1}\\s*&&\\s*\\$key\\s*!=\\s*['\"]{0,1}smtp_port")
   (notify WebShell))
  (if
   (bodymask () "echo['\"]{0,1}<center><b>Done\\s*==>\\s*\\$userfile_name")
   (notify WebShell))
  (if (bodymask () "['\"]e/\\*\\./['\"]") (notify WebShell))
  (if (bodymask () "assert\\s*\\(\\s*@*stripslashes") (notify WebShell))
  (if
   (bodymask ()
    "\\)\\s*\\.\\s*substr\\s*\\(\\s*md5\\s*\\(\\s*strrev\\s*\\(\\s*\\$")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$fl\\s*=\\s*\"<meta http-equiv=\\\\\"Refresh\\\\\"\\s+content=\\\\\"0;\\s*URL=")
   (notify WebShell))
  (if
   (bodymask ()
    ",\\s*array\\s*\\('\\.','\\.\\.','Thumbs\\.db'\\)\\s*\\)\\s*\\)\\s*{\\s*continue;\\s*}\\s*if\\s*\\(\\s*is_file")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\s*\\(\\s*\\$dataSize\\s*<\\s*BOTCRYPT_MAX_SIZE\\s*\\)\\s*rc4\\s*\\(\\s*\\$data,\\s*\\$cryptkey")
   (notify WebShell))
  (if (bodymask () "str_rot13\\s*\\(\\s*['\"]{0,1}tmvasyng['\"]{0,1}")
   (notify WebShell))
  (if (bodymask () "str_rot13\\s*\\(\\s*['\"]{0,1}onfr64_qrpbqr['\"]{0,1}")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\s*\\(\\s*\\$_POST\\[\\s*['\"]{0,1}path['\"]{0,1}\\s*\\]\\s*==\\s*['\"]{0,1}['\"]{0,1}\\s*\\)\\s*{\\s*\\$uploadfile\\s*=\\s*\\$_FILES\\[\\s*['\"]{0,1}file['\"]{0,1}\\s*\\]\\[\\s*['\"]{0,1}name['\"]{0,1}\\s*\\]")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\s*\\(\\s*fwrite\\s*\\(\\s*\\$handle\\s*,\\s*file_get_contents\\s*\\(\\s*\\$_(GET|POST|SERVER|COOKIE|REQUEST)")
   (notify WebShell))
  (if
   (bodymask ()
    "array_key_exists\\s*\\(\\s*\\$fileRas\\s*,\\s*\\$fileType\\)\\s*\\?\\s*\\$fileType\\[\\s*\\$fileRas\\s*\\]")
   (notify WebShell))
  (if
   (bodymask ()
    "urlencode\\(print_r\\(array\\(\\),1\\)\\),5,1\\)\\.c\\),\\$c\\);}eval\\(\\$d\\)")
   (notify WebShell))
  (if (bodymask () "if\\s*\\(\\s*function_exists\\s*\\(\\s*'pcntl_fork")
   (notify WebShell))
  (if (bodymask () "find\\s+/\\s+-type\\s+f\\s+-perm\\s+-04000\\s+-ls")
   (notify WebShell))
  (if
   (bodymask ()
    "execl\\(['\"]/bin/sh['\"]\\s*,\\s*['\"]/bin/sh['\"]\\s*,\\s*['\"]-i['\"]\\s*,\\s*0\\)")
   (notify WebShell))
  (if (bodymask () "function\\s+inject\\(\\$file,\\s*\\$injection=")
   (notify WebShell))
  (if (bodymask () "fclose\\(\\$f\\);\\s*echo\\s*['\"]o\\.k\\.['\"]")
   (notify WebShell))
  (if
   (bodymask ()
    "preg_replace\\s*\\(\\s*\\$exif\\[\\s*\\\\['\"]Make\\\\['\"]\\s*\\]\\s*,\\s*\\$exif\\[\\s*\\\\['\"]Model\\\\['\"]\\s*\\]")
   (notify WebShell))
  (if
   (bodymask ()
    "\\^downloads/\\(\\[0-9\\]\\*\\)/\\(\\[0-9\\]\\*\\)/\\$\\s+downloads\\.php\\?c=\\$1&p=\\$2")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$res=mysql_query\\(['\"]{0,1}SELECT\\s+\\*\\s+FROM\\s+`watchdog_old_05`\\s+WHERE\\s+page")
   (notify WebShell))
  (if
   (bodymask ()
    "RewriteRule\\s+\\.\\*\\s+index\\.php\\?url=\\$0\\s+\\[L,QSA\\]")
   (notify WebShell))
  (if
   (bodymask ()
    "IO::Socket::INET->new\\(Proto\\s*=>\\s*\"tcp\"\\s*,\\s*LocalPort\\s*=>\\s*36000\\s*,\\s*Listen\\s*=>\\s*SOMAXCONN")
   (notify WebShell))
  (if (bodymask () "eval\\s*\\(*\\s*strrev\\s*\\(*\\s*str_replace")
   (notify WebShell))
  (if
   (bodymask ()
    "@*move_uploaded_file\\s*\\(\\s*\\$_FILES\\[\\s*['\"]{0,1}message['\"]{0,1}\\s*\\]\\[\\s*['\"]{0,1}tmp_name['\"]{0,1}\\s*\\]\\s*,\\s*\\$security_code\\s*\\.\\s*\"/\"\\s*\\.\\s*\\$_FILES\\[['\"]{0,1}message['\"]{0,1}\\]\\[['\"]{0,1}name['\"]{0,1}\\]\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$URL\\s*=\\s*\\$urls\\[\\s*rand\\(\\s*0\\s*,\\s*count\\s*\\(\\s*\\$urls\\s*\\)\\s*-\\s*1\\s*\\)\\s*\\]")
   (notify WebShell))
  (if
   (bodymask ()
    "isset\\s*\\(\\s*\\$_FILES\\[\\s*['\"]{0,1}x['\"]{0,1}\\s*\\]\\s*\\)\\s*\\?\\s*\\(\\s*is_uploaded_file\\s*\\(\\s*\\$_FILES\\[\\s*['\"]{0,1}x['\"]{0,1}\\s*\\]\\[\\s*['\"]{0,1}tmp_name['\"]{0,1}\\s*\\]\\s*\\)\\s*\\?\\s*\\(\\s*copy\\s*\\(\\s*\\$_FILES\\[\\s*['\"]{0,1}x['\"]{0,1}\\s*\\]")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\s*\\(\\s*\\$i\\s*<\\s*\\(\\s*count\\s*\\(\\s*\\$_POST\\[\\s*['\"]{0,1}q['\"]{0,1}\\s*\\]\\s*\\)\\s*-\\s*1")
   (notify WebShell))
  (if
   (bodymask ()
    "file_get_contents\\s*\\(*\\s*ADMIN_REDIR_URL\\s*,\\s*false\\s*,\\s*\\$ctx\\s*\\)")
   (notify WebShell))
  (if (bodymask () tmhapbzcerff) (notify WebShell))
  (if
   (bodymask ()
    "content=['\"]{0,1}no-cache['\"]{0,1};\\s*\\$config\\[['\"]{0,1}description['\"]{0,1}\\]\\s*\\.=\\s*['\"]{0,1}")
   (notify WebShell))
  (if
   (bodymask ()
    "clearstatcache\\(\\s*\\);\\s*if\\s*\\(\\s*!is_dir\\s*\\(\\s*\\$fld\\s*\\)\\s*\\)\\s*return")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$rBuffLen\\s*=\\s*ord\\s*\\(\\s*VC_Decrypt\\s*\\(\\s*fread\\s*\\(\\s*\\$input,\\s*1\\s*\\)\\s*\\)\\s*\\)\\s*\\*\\s*256")
   (notify WebShell))
  (if (bodymask () IrSecTeam) (notify WebShell))
  (if
   (bodymask ()
    "@header\\(['\"]Location:\\s*['\"]\\.['\"]h['\"]\\.['\"]t['\"]\\.['\"]t['\"]\\.['\"]p['\"]")
   (notify WebShell))
  (if
   (bodymask ()
    "set_time_limit\\s*\\(\\s*0\\s*\\);\\s*if\\s*\\(!SecretPageHandler::checkKey")
   (notify WebShell))
  (if
   (bodymask ()
    "return\\s*\\(\\s*strstr\\s*\\(\\s*\\$s\\s*,\\s*'echo'\\s*\\)\\s*==\\s*false\\s*\\?\\s*\\(\\s*strstr\\s*\\(\\s*\\$s\\s*,\\s*'print'")
   (notify WebShell))
  (if
   (bodymask ()
    "time\\(\\)\\s*\\+\\s*10000\\s*,\\s*['\"]/['\"]\\);\\s*echo\\s+\\$m_zz;\\s*eval\\s*\\(\\$m_zz")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\(!empty\\(\\$_FILES\\[['\"]{0,1}message['\"]{0,1}\\]\\[['\"]{0,1}name['\"]{0,1}\\]\\)\\s+AND\\s+\\(md5\\(\\$_POST\\[['\"]{0,1}nick['\"]{0,1}\\]\\)\\s*==\\s*['\"]{0,1}")
   (notify WebShell))
  (if (bodymask () "str_rot13\\s*\\(\\s*gzinflate\\s*\\(\\s*base64_decode")
   (notify WebShell))
  (if
   (bodymask () "gzuncompress\\s*\\(\\s*str_rot13\\s*\\(\\s*base64_decode")
   (notify WebShell))
  (if
   (bodymask () "gzuncompress\\s*\\(\\s*base64_decode\\s*\\(\\s*str_rot13")
   (notify WebShell))
  (if
   (bodymask ()
    "gzinflate\\s*\\(\\s*base64_decode\\s*\\(\\s*str_rot13\\s*\\(\\s*strrev")
   (notify WebShell))
  (if
   (bodymask ()
    "gzinflate\\s*\\(\\s*base64_decode\\s*\\(\\s*strrev\\s*\\(\\s*str_rot13")
   (notify WebShell))
  (if (bodymask () "gzinflate\\s*\\(\\s*base64_decode\\s*\\(\\s*strrev")
   (notify WebShell))
  (if
   (bodymask ()
    "gzinflate\\s*\\(\\s*base64_decode\\s*\\(\\s*base64_decode\\s*\\(\\s*str_rot13")
   (notify WebShell))
  (if
   (bodymask ()
    "base64_decode\\s*\\(\\s*gzuncompress\\s*\\(\\s*base64_decode")
   (notify WebShell))
  (if (bodymask () "gzinflate\\s*\\(\\s*base64_decode\\s*\\(\\s*str_rot13")
   (notify WebShell))
  (if (bodymask () "gzinflate\\s*\\(\\s*str_rot13\\s*\\(\\s*base64_decode")
   (notify WebShell))
  (if (bodymask () "Brazil\\s+HackTeam") (notify WebShell))
  (if
   (bodymask ()
    "\\$tld\\s*=\\s*array\\s*\\(\\s*['\"]com['\"],['\"]org['\"],['\"]net['\"]")
   (notify WebShell))
  (if (bodymask () "define\\s*\\(*\\s*['\"]SBCID_REQUEST_FILE['\"]\\s*,")
   (notify WebShell))
  (if (bodymask () "preg_replace\\s*\\(*\\s*['\"]/\\.\\+/esi")
   (notify WebShell))
  (if (bodymask () "Mysterious\\s+Wire") (notify WebShell))
  (if
   (bodymask ()
    "\\$headers\\s*\\.=\\s*\\$_POST\\[\\s*['\"]eMailAdd['\"]\\s*\\]")
   (notify WebShell))
  (if (bodymask () "define\\s*\\(\\s*['\"]DEFCALLBACKMAIL")
   (notify WebShell))
  (if (bodymask () "default_action\\s*=\\s*['\"]{0,1}FilesMan['\"]{0,1}")
   (notify WebShell))
  (if (bodymask () "echo\\s+@file_get_contents\\s*\\(\\s*\\$get")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\s*\\(\\s*stripos\\s*\\(\\s*\\$_SERVER\\[['\"]{0,1}HTTP_USER_AGENT['\"]{0,1}\\]\\s*,\\s*['\"]{0,1}Android['\"]{0,1}\\)\\s*!==false\\s*&&\\s*!\\$_COOKIE\\[['\"]{0,1}dle_user_id")
   (notify WebShell))
  (if
   (bodymask ()
    "header\\s*\\(['\"]Location:\\s*['\"]\\s*\\.\\s*\\$to\\s*\\.\\s*urldecode")
   (notify WebShell))
  (if (bodymask () "Dc0RHa['\"]") (notify WebShell))
  (if (bodymask () "!touch\\(['\"]{0,1}\\.\\./\\.\\./language/")
   (notify WebShell))
  (if (bodymask () "eval\\(\\s*stripslashes\\(\\s*\\\\\\$_REQUEST")
   (notify WebShell))
  (if
   (bodymask ()
    "document\\.write\\s*\\(\\s*['\"]{0,1}<script\\s+src=['\"]{0,1}http://<\\?=\\$domain\\?>/")
   (notify WebShell))
  (if
   (bodymask ()
    "exit\\s*\\(\\s*['\"]{0,1}<script>\\s*setTimeout\\s*\\(\\s*\\\\['\"]{0,1}document\\.location\\.href")
   (notify WebShell))
  (if (bodymask () "function\\s+sql2_safe\\s*\\(") (notify WebShell))
  (if (bodymask () "\\$postResult\\s*=\\s*curl_exec\\s*\\(*\\s*\\$ch")
   (notify WebShell))
  (if
   (bodymask ()
    "&&\\s*function_exists\\s*\\(*\\s*['\"]{0,1}getmxrr['\"]{0,1}\\)\\s*\\)\\s*{\\s*@getmxrr\\s*\\(*\\s*\\$")
   (notify WebShell))
  (if
   (bodymask ()
    "is__writable\\s*\\(*\\s*\\$path\\s*\\.\\s*uniqid\\s*\\(*\\s*mt_rand")
   (notify WebShell))
  (if (bodymask () "file_put_contentz\\s*\\(*\\s*\\$") (notify WebShell))
  (if
   (bodymask ()
    "@*gzinflate\\s*\\(\\s*@*base64_decode\\s*\\(\\s*@*str_replace")
   (notify WebShell))
  (if
   (bodymask ()
    "fopen\\s*\\(*\\s*['\"]http://['\"]\\s*\\.\\s*\\$check_domain\\s*\\.\\s*['\"]:80['\"]\\s*\\.\\s*\\$check_doc\\s*,\\s*['\"]r['\"]")
   (notify WebShell))
  (if (bodymask () "@\\$_COOKIE\\[['\"]{0,1}statCounter['\"]{0,1}\\]")
   (notify WebShell))
  (if (bodymask () "if\\s*\\(*\\s*@*preg_match\\s*\\(*\\s*str")
   (notify WebShell))
  (if
   (bodymask ()
    "array_pop\\s*\\(*\\s*\\$workReplace\\s*,\\s*\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\s*,\\s*\\$countKeysNew")
   (notify WebShell))
  (if
   (bodymask ()
    "(GET|POST|SERVER|COOKIE|REQUEST)\\s*\\[\\s*['\"]___['\"]\\s*")
   (notify WebShell))
  (if (bodymask () "\\(\\s*['\"]INSHELL['\"]\\s*") (notify WebShell))
  (if
   (bodymask ()
    "\\$b\\s*\\.\\s*\\$p\\s*\\.\\s*\\$h\\s*\\.\\s*\\$k\\s*\\.\\s*\\$v")
   (notify WebShell))
  (if
   (bodymask ()
    "=\\s*preg_split\\s*\\(\\s*['\"]/\\\\,\\(\\\\ \\+\\)\\?/['\"],\\s*@*ini_get\\s*\\(\\s*['\"]disable_functions")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\s*\\(!function_exists\\s*\\(\\s*['\"]posix_getpwuid['\"]\\s*\\)\\s*&&\\s*!in_array\\s*\\(\\s*['\"]posix_getpwuid")
   (notify WebShell))
  (if
   (bodymask ()
    "preg_replace\\s*\\(\\s*['\"]/\\^\\(www\\|ftp\\)\\\\\\./i['\"]\\s*,\\s*['\"]['\"],\\s*@\\$_SERVER\\s*\\[\\s*['\"]{0,1}HTTP_HOST['\"]{0,1}\\s*\\]\\s*\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\s*\\(*\\s*isset\\s*\\(*\\s*\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\s*\\[\\s*['\"]{0,1}[a-zA-Z_0-9]+['\"]{0,1}\\s*\\]\\s*\\)*\\s*\\)\\s*{\\s*\\$[a-zA-Z_0-9]+\\s*=\\s*\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\s*\\[\\s*['\"]{0,1}[a-zA-Z_0-9]+['\"]{0,1}\\s*\\];\\s*eval\\s*\\(*\\s*\\$[a-zA-Z_0-9]+\\s*\\)*")
   (notify WebShell))
  (if
   (bodymask ()
    "eval\\s*\\(*\\s*stripslashes\\s*\\(*\\s*array_pop\\(*\\$_(GET|POST|SERVER|COOKIE|REQUEST)")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\s+\\(\\s*strpos\\s*\\(\\s*\\$url\\s*,\\s*['\"]js/mootools\\.js['\"]\\s*\\)\\s*===\\s*false\\s+&&\\s+strpos\\s*\\(\\s*\\$url\\s*,\\s*['\"]js/caption\\.js['\"]{0,1}")
   (notify WebShell))
  (if
   (bodymask ()
    "if\\s+\\(*\\s*mail\\s*\\(\\s*\\$recp\\s*,\\s*\\$subj\\s*,\\s*\\$stunt\\s*,\\s*\\$frm")
   (notify WebShell))
  (if (bodymask () "<\\?php\\s+\\$_F\\s*=\\s*__FILE__\\s*;\\s*\\$_X\\s*=")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$x\\d+\\s*=\\s*['\"].+?['\"]\\s*;\\s*\\$x\\d+\\s*=\\s*['\"].+?['\"]\\s*;\\s*\\$x\\d+\\s*=\\s*['\"]")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$beecode\\s*=@*file_get_contents\\s*\\(*['\"]{0,1}\\s*\\$urlpurs\\s*['\"]{0,1}\\)*\\s*;\\s*echo\\s+['\"]{0,1}\\$beecode['\"]{0,1}")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$GLOBALS\\[\\s*['\"]{0,1}.+?['\"]{0,1}\\s*\\]\\[\\s*\\d+\\s*\\]\\(\\s*\\$_\\d+\\s*,\\s*_\\d+\\s*\\(\\s*\\d+\\s*\\)\\s*\\)\\s*\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "preg_replace\\s*\\(*\\s*['\"]{0,1}/\\.\\*\\[.+?\\]\\?/e['\"]{0,1}\\s*,\\s*str_replace")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$GLOBALS\\[['\"]{0,1}.+?['\"]{0,1}\\]=Array\\s*\\(\\s*base64_decode\\s*\\(\\s*['\"]{0,1}.+?['\"]{0,1}\\s*\\)\\s*,\\s*base64_decode\\s*\\(\\s*['\"]{0,1}.+?['\"]{0,1}\\s*\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "UNION\\s+SELECT\\s+['\"]{0,1}0['\"]{0,1}\\s*,\\s*['\"]{0,1}<\\? system\\(\\\\\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\[cpc\\]\\);exit;\\s*\\?>['\"]{0,1}\\s*,\\s*0\\s*,0\\s*,\\s*0\\s*,\\s*0\\s+INTO\\s+OUTFILE\\s+['\"]{0,1}\\$['\"]{0,1}")
   (notify WebShell))
  (if
   (bodymask ()
    "isset\\s*\\(*\\s*\\$_POST\\s*\\[\\s*['\"]{0,1}execgate['\"]{0,1}\\s*\\]\\s*\\)*")
   (notify WebShell))
  (if
   (bodymask ()
    "fwrite\\s*\\(*\\s*\\$fpsetv\\s*,\\s*getenv\\s*\\(\\s*['\"]HTTP_COOKIE['\"]\\s*\\)\\s*")
   (notify WebShell))
  (if (bodymask () "symlink\\s*\\(*\\s*['\"]/home/") (notify WebShell))
  (if
   (bodymask ()
    "function\\s+urlGetContents\\s*\\(*\\s*\\$url\\s*,\\s*\\$timeout\\s*=\\s*\\d+\\s*\\)")
   (notify WebShell))
  (if (bodymask () "strrev\\(*\\s*['\"]{0,1}edoced_46esab['\"]{0,1}\\s*\\)*")
   (notify WebShell))
  (if (bodymask () "strrev\\(*\\s*['\"]{0,1}tressa['\"]{0,1}\\s*\\)*")
   (notify WebShell))
  (if (bodymask () "exec\\s*\\(\\s*['\"]ipfw") (notify WebShell))
  (if
   (bodymask ()
    "wp_posts\\s+WHERE\\s+post_type\\s*=\\s*['\"]{0,1}post['\"]{0,1}\\s+AND\\s+post_status\\s*=\\s*['\"]{0,1}publish['\"]{0,1}\\s+ORDER\\s+BY\\s+`ID`\\s+DESC")
   (notify WebShell))
  (if
   (bodymask ()
    "file_get_contents\\s*\\(*\\s*trim\\s*\\(\\s*\\$.+?\\[\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\[['\"]{0,1}.+?['\"]{0,1}\\]\\]\\)\\);")
   (notify WebShell))
  (if
   (bodymask ()
    "is_callable\\s*\\(*\\s*['\"]{0,1}(ftp_exec|system|shell_exec|passthru|popen|proc_open)['\"]{0,1}\\)*\\s+and\\s+!in_array\\s*\\(*\\s*['\"]{0,1}(ftp_exec|system|shell_exec|passthru|popen|proc_open)['\"]{0,1}\\s*,\\s*\\$disablefuncs")
   (notify WebShell))
  (if (bodymask () "\\$GLOBALS\\[['\"]{0,1}____") (notify WebShell))
  (if (bodymask () "fopen\\s*\\(*\\s*['\"]{0,1}/etc/passwd['\"]{0,1}")
   (notify WebShell))
  (if
   (bodymask ()
    "eval\\s*\\(*@*\\s*stripslashes\\s*\\(*\\s*array_pop\\s*\\(*\\s*@*\\$_")
   (notify WebShell))
  (if (bodymask () "eval\\s*\\(*@*\\s*stripslashes\\s*\\(*\\s*@*\\$_")
   (notify WebShell))
  (if
   (bodymask ()
    "@*setcookie\\s*\\(*\\s*['\"]{0,1}hit['\"]{0,1},\\s*1\\s*,\\s*time\\s*\\(*\\s*\\)*\\s*\\+")
   (notify WebShell))
  (if (bodymask () "eval\\s*\\(*\\s*file_get_contents\\s*\\(*")
   (notify WebShell))
  (if (bodymask () "preg_replace\\s*\\(*\\s*['\"]{0,1}/\\.\\*/e['\"]{0,1}")
   (notify WebShell))
  (if
   (bodymask ()
    "\\s*{\\s*\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\s*\\[\\s*['\"]{0,1}root['\"]{0,1}\\s*\\]\\s*}")
   (notify WebShell))
  (if
   (bodymask ()
    "['\"]{0,1}httpd\\.conf['\"]{0,1}\\s*,\\s*['\"]{0,1}vhosts\\.conf['\"]{0,1}\\s*,\\s*['\"]{0,1}cfg\\.php['\"]{0,1}\\s*,\\s*['\"]{0,1}config\\.php['\"]{0,1}")
   (notify WebShell))
  (if (bodymask () "proc_open\\s*\\(\\s*['\"]{0,1}IHSteam")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$ini\\s*\\[\\s*['\"]{0,1}users['\"]{0,1}\\s*\\]\\s*=\\s*array\\s*\\(\\s*['\"]{0,1}root['\"]{0,1}\\s*=>")
   (notify WebShell))
  (if
   (bodymask ()
    "curl_setopt\\s*\\(\\s*\\$ch\\s*,\\s*CURLOPT_URL\\s*,\\s*['\"]{0,1}http://\\$host:\\d+['\"]{0,1}\\s*\\)")
   (notify WebShell))
  (if (bodymask () "system\\s*\\(*\\s*['\"]{0,1}whoami['\"]{0,1}\\s*\\)*")
   (notify WebShell))
  (if
   (bodymask ()
    "find\\s+/\\s+-name\\s+\\.ssh\\s+>\\s+\\$dir/sshkeys/sshkeys")
   (notify WebShell))
  (if
   (bodymask () "assert\\s*\\(*\\s*@*\\$_(GET|POST|SERVER|COOKIE|REQUEST)")
   (notify WebShell))
  (if (bodymask () "eval\\s*\\(*\\s*@*\\$_(GET|POST|SERVER|COOKIE|REQUEST)")
   (notify WebShell))
  (if (bodymask () "php\\s+\"\\s*\\.\\s*\\$wso_path") (notify WebShell))
  (if
   (bodymask ()
    "@*assert\\s*\\(*\\s*\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\s*\\[\\s*['\"]{0,1}.+?['\"]{0,1}\\s*\\]\\s*")
   (notify WebShell))
  (if (bodymask () eva1[a-zA-Z0-9_]+?Sir) (notify WebShell))
  (if
   (bodymask ()
    "\\$cmd\\s*=\\s*\\(\\s*@*\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\s*\\[\\s*['\"]{0,1}.+?['\"]{0,1}\\s*\\]\\s*\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$function\\s*\\(*\\s*@*\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\s*\\[\\s*['\"]{0,1}cmd['\"]{0,1}\\s*\\]\\s*\\)*")
   (notify WebShell))
  (if (bodymask () "\\$fe\\(\"\\$cmd\\s+2>&1\"\\);") (notify WebShell))
  (if
   (bodymask ()
    "(ftp_exec|system|shell_exec|passthru|popen|proc_open)\\(['\"]\\$cmd\\s+1>\\s*/tmp/cmdtemp\\s+2>&1;\\s*cat\\s+/tmp/cmdtemp;\\s*rm\\s+/tmp/cmdtemp['\"]\\);")
   (notify WebShell))
  (if
   (bodymask ()
    "setcookie\\(*\\s*['\"]mysql_web_admin_username['\"]\\s*\\)*")
   (notify WebShell))
  (if
   (bodymask ()
    "(ftp_exec|system|shell_exec|passthru|popen|proc_open)\\s*\\(*\\s*['\"]uname\\s+-a['\"]\\s*\\)*")
   (notify WebShell))
  (if
   (bodymask ()
    "(ftp_exec|system|shell_exec|passthru|popen|proc_open)\\s*\\(*\\s*@*\\$_POST\\s*\\[\\s*['\"].+?['\"]\\s*\\]\\s*\\.\\s*\"\\s*2\\s*>\\s*&1\\s*['\"]")
   (notify WebShell))
  (if
   (bodymask ()
    "!@*\\$_REQUEST\\s*\\[\\s*['\"]c99sh_surl['\"]\\s*\\]\\s*\\)")
   (notify WebShell))
  (if (bodymask () "\\$login\\s*=\\s*@*posix_getuid\\(*\\s*\\)*")
   (notify WebShell))
  (if (bodymask () "ncftpput\\s*-u\\s*\\$ftp_user_name") (notify WebShell))
  (if
   (bodymask ()
    "runcommand\\s*\\(\\s*['\"]shellhelp['\"]\\s*,\\s*['\"](GET|POST|SERVER|COOKIE|REQUEST)['\"]")
   (notify WebShell))
  (if
   (bodymask ()
    "{\\s*\\$\\s*{\\s*passthru\\s*\\(*\\s*\\$cmd\\s*\\)\\s*}\\s*}\\s*<br>")
   (notify WebShell))
  (if
   (bodymask ()
    "passthru\\s*\\(*\\s*getenv\\s*\\(*\\s*\\\\['\"]HTTP_ACCEPT_LANGUAGE")
   (notify WebShell))
  (if
   (bodymask ()
    "passthru\\s*\\(*\\s*getenv\\s*\\(*\\s*['\"]HTTP_ACCEPT_LANGUAGE")
   (notify WebShell))
  (if
   (bodymask ()
    "SELECT\\s+1\\s+FROM\\s+mysql\\.user\\s+WHERE\\s+concat\\(\\s*`user`\\s*,\\s*'@'\\s*,\\s*`host`\\s*\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$MessageSubject\\s*=\\s*base64_decode\\s*\\(\\s*\\$_POST\\s*\\[\\s*['\"]{0,1}msgsubject['\"]{0,1}\\s*\\]\\s*\\)")
   (notify WebShell))
  (if (bodymask () "rename\\s*\\(\\s*\\s*['\"]{0,1}wso\\.php['\"]{0,1}\\s*,")
   (notify WebShell))
  (if
   (bodymask ()
    "filepath\\s*=\\s*@*realpath\\s*\\(\\s*\\$_POST\\s*\\[\\s*['\"]filepath['\"]\\s*\\]\\s*\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "filepath\\s*=\\s*@*realpath\\s*\\(\\s*\\$_POST\\s*\\[\\s*\\\\['\"]filepath\\\\['\"]\\s*\\]\\s*\\)")
   (notify WebShell))
  (if (bodymask () "eval\\s*\\(*\\s*base64_decode\\s*\\(*\\s*@*\\$_")
   (notify WebShell))
  (if
   (bodymask ()
    "wsoEx\\s*\\(\\s*\\\\['\"]\\s*tar\\s*cfzv\\s*\\\\['\"]\\s*\\.\\s*escapeshellarg\\s*\\(\\s*\\$_POST\\[\\s*\\\\['\"]p2\\\\['\"]\\s*\\]\\s*\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "WSOsetcookie\\s*\\(\\s*md5\\s*\\(\\s*@*\\$_SERVER\\[\\s*['\"]HTTP_HOST['\"]\\s*\\]\\s*\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "WSOsetcookie\\s*\\(\\s*md5\\s*\\(\\s*@*\\$_SERVER\\[\\s*\\\\['\"]HTTP_HOST\\\\['\"]\\s*\\]\\s*\\)")
   (notify WebShell))
  (if
   (bodymask ()
    "\\$info \\.= \\(\\(\\$perms\\s*&\\s*0x0040\\)\\s*\\?\\(\\(\\$perms\\s*&\\s*0x0800\\)\\s*\\?\\s*\\\\['\"]s\\\\['\"]\\s*:\\s*\\\\['\"]x\\\\['\"]\\s*\\)\\s*:\\(\\(\\$perms\\s*&\\s*0x0800\\)\\s*\\?\\s*'S'\\s*:\\s*'-'\\s*\\)")
   (notify WebShell))
  (if (bodymask () "default_action\\s*=\\s*\\\\['\"]FilesMan")
   (notify WebShell))
  (if (bodymask () "system\\s+file\\s+do\\s+not\\s+delete")
   (notify WebShell))
  (if (bodymask () "hacked\\s+by\\s+Hmei7") (notify WebShell))
  (if (bodymask () "by\\s+Grinay") (notify WebShell))
  (if (bodymask () "Captain\\s+Crunch\\s+Team") (notify WebShell))
  (if
   (bodymask ()
    "\\$_(GET|POST|SERVER|COOKIE|REQUEST)\\[\\s*['\"]{0,1}p2['\"]{0,1}\\s*\\]\\s*==\\s*['\"]{0,1}chmod['\"]{0,1}")
   (notify WebShell))
  (if
   (bodymask ()
    "userAgent\\|pp\\|http\\|dazalyz['\"]{0,1}\\.split\\(['\"]{0,1}\\|['\"]{0,1}\\),0")
   (notify "JS Virus"))
  (if (bodymask () "f='f'\\+'r'\\+'o'\\+'m'\\+'Ch'\\+'arC'\\+'ode';")
   (notify "JS Virus"))
  (if (bodymask () "\\.prototype\\.a}catch\\(") (notify "JS Virus"))
  (if (bodymask () "try{Boolean\\(\\)\\.prototype\\.q}catch\\(")
   (notify "JS Virus"))
  (if (bodymask () "if\\(Ref\\.indexOf\\('\\.google\\.'\\)!=")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "indexOf\\|if\\|rc\\|length\\|msn\\|yahoo\\|referrer\\|altavista\\|ogo\\|bi\\|hp\\|var\\|aol\\|query")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "Array\\.prototype\\.slice\\.call\\(arguments\\)\\.join\\(\"\"\\)")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "q=document\\.createElement\\(\"d\"\\+\"i\"\\+\"v\"\\);q\\.appendChild\\(q\\+\"\"\\);}catch\\(qw\\){h=")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "\\+zz;ss=\\[\\];f='fr'\\+'om'\\+'Ch';f\\+='arC';f\\+='ode';w=this;e=w\\[f\\[\"substr\"\\]\\(")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "s5\\(q5\\){return \\+\\+q5;}function yf\\(sf,we\\){return sf\\.substr\\(we,1\\);}function y1\\(wb\\){if\\(wb==168\\)wb=1025;else")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "if\\(navigator\\.userAgent\\.match\\(/\\(android\\|midp\\|j2me\\|symbian")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "document\\.write\\('<script language=\"JavaScript\" type=\"text/javascript\" src=\"'\\+domain\\+'\"></scr'\\+'ipt>'\\)")
   (notify "JS Virus"))
  (if (bodymask () "http://phsp\\.ru/_/go\\.php\\?sid=") (notify "JS Virus"))
  (if (bodymask () "</html>\\s*<script") (notify "JS Virus"))
  (if (bodymask () "</html>\\s*<iframe") (notify "JS Virus"))
  (if
   (bodymask ()
    "=navigator\\[appVersion_var\\]\\.indexOf\\(\"MSIE\"\\)!=-1\\?'<iframe name")
   (notify "JS Virus"))
  (if (bodymask () "\\\\x65At") (notify "JS Virus"))
  (if (bodymask () "\\\\x61rCod") (notify "JS Virus"))
  (if (bodymask () "\"fr\"\\+\"omC\"\\+\"harCode\"") (notify "JS Virus"))
  (if (bodymask () "=\"ev\"\\+\"al\"") (notify "JS Virus"))
  (if
   (bodymask ()
    "\\[\\(\\(e\\)\\?\"s\":\"\"\\)\\+\"p\"\\+\"lit\"\\]\\(\"a\\$\"\\[\\(\\(e\\)\\?\"su\":\"\"\\)\\+\"bstr\"\\]\\(1\\)\\);")
   (notify "JS Virus"))
  (if (bodymask () "f='fr'\\+'om'\\+'Ch';f\\+='arC';f\\+='ode';")
   (notify "JS Virus"))
  (if (bodymask () "f\\+=\\(h\\)\\?'ode':\"\";") (notify "JS Virus"))
  (if (bodymask () "f='f'\\+'r'\\+'o'\\+'m'\\+'Ch'\\+'arC'\\+'ode';")
   (notify "JS Virus"))
  (if
   (bodymask () "f='fromCh';f\\+='arC';f\\+='qgode'\\[\"substr\"\\]\\(2\\);")
   (notify "JS Virus"))
  (if (bodymask () "var\\s+div_colors") (notify "JS Virus"))
  (if (bodymask () "var\\s+_0x") (notify "JS Virus"))
  (if (bodymask () CoreLibrariesHandler) (notify "JS Virus"))
  (if (bodymask () pingnow) (notify "JS Virus"))
  (if (bodymask () serchbot) (notify "JS Virus"))
  (if (bodymask () km0ae9gr6m) (notify "JS Virus"))
  (if (bodymask () c3284d) (notify "JS Virus"))
  (if (bodymask () "\\\\x68arC") (notify "JS Virus"))
  (if (bodymask () "\\\\x6dCha") (notify "JS Virus"))
  (if (bodymask () "\\\\x6fde") (notify "JS Virus"))
  (if (bodymask () "\\\\x6fde") (notify "JS Virus"))
  (if (bodymask () "\\\\x43ode") (notify "JS Virus"))
  (if (bodymask () "\\\\x72om") (notify "JS Virus"))
  (if (bodymask () "\\\\x43ha") (notify "JS Virus"))
  (if (bodymask () "\\\\x72Co") (notify "JS Virus"))
  (if (bodymask () "\\\\x43ode") (notify "JS Virus"))
  (if (bodymask () "\\.dyndns\\.") (notify "JS Virus"))
  (if (bodymask () "\\.dyndns-") (notify "JS Virus"))
  (if
   (bodymask ()
    "}\\s*else\\s*{\\s*document\\.write\\s*\\(\\s*['\"]{0,1}\\.['\"]{0,1}\\)\\s*}\\s*}\\s*R\\(\\s*\\)")
   (notify "JS Virus"))
  (if (bodymask () "document\\.write\\(unescape\\('%3Cdiv%20id%3D%22")
   (notify "JS Virus"))
  (if (bodymask () "\\.bitcoinplus\\.com") (notify "JS Virus"))
  (if (bodymask () "\\.split\\(\"&&\"\\);h=2;s=\"\";if\\(m\\)for\\(i=0;")
   (notify "JS Virus"))
  (if (bodymask () "<iframe\\s+src=\"http://deluxesclicks\\.pro/")
   (notify "JS Virus"))
  (if (bodymask () "3Bfor\\|fromCharCode\\|2C27\\|3D\\|2C88\\|unescape")
   (notify "JS Virus"))
  (if
   (bodymask ()
    ";\\s*document\\.write\\(['\"]{0,1}<iframe\\s*src=\"http://ya\\.ru")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "w\\.document\\.body\\.appendChild\\(script\\);\\s*clearInterval\\(i\\);\\s*}\\s*}\\s*,\\s*\\d+\\s*\\)\\s*;\\s*}\\s*\\)\\(\\s*window")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "if\\(!g\\(\\)&&window\\.navigator\\.cookieEnabled\\){document\\.cookie=\"1=1;expires=\"\\+e\\.toGMTString\\(\\)\\+\";path=/\";")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "nn_param_preloader_container\\|5001\\|hidden\\|innerHTML\\|inject\\|visible")
   (notify "JS Virus"))
  (if (bodymask () "<!-- [a-zA-Z0-9_]+?\\|\\|stat -->") (notify "JS Virus"))
  (if
   (bodymask ()
    "&parameter=\\$keyword&se=\\$se&ur=1&HTTP_REFERER='\\+encodeURIComponent\\(document\\.URL\\)")
   (notify "JS Virus"))
  (if (bodymask () "windows\\|series\\|60\\|symbos\\|ce\\|mobile\\|symbian")
   (notify "JS Virus"))
  (if (bodymask () "\\[['\"]eval['\"]\\]\\(s\\);}}}}</script>")
   (notify "JS Virus"))
  (if
   (bodymask () kC70FMblyJkFWZodCKl1WYOdWYUlnQzRnbl1WZsVEdldmL05WZtV3YvRGI9)
   (notify "JS Virus"))
  (if
   (bodymask ()
    "{k=i;s=s\\.concat\\(ss\\(eval\\(asq\\(\\)\\)-1\\)\\);}z=s;eval\\(")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "document\\.cookie\\.match\\(new\\s+RegExp\\(\\s*\"\\(\\?:\\^\\|; \\)\"\\s*\\+\\s*name\\.replace\\(/\\(\\[\\\\\\.\\$\\?\\*\\|{}\\\\\\(\\\\\\)\\\\\\[\\\\\\]\\\\/\\\\\\+\\^\\]\\)/g")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "setCookie\\s*\\(*\\s*\"arx_tt\"\\s*,\\s*1\\s*,\\s*dt\\.toGMTString\\(\\)\\s*,\\s*['\"]{0,1}/['\"]{0,1}")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "document\\.cookie\\.match\\s*\\(\\s*new\\s+RegExp\\s*\\(\\s*\"\\(\\?:\\^\\|;\\s*\\)\"\\s*\\+\\s*name\\.replace\\s*\\(/\\(\\[\\\\\\.\\$\\?\\*\\|{}\\\\\\(\\\\\\)\\\\\\[\\\\\\]\\\\/\\\\\\+\\^\\]\\)/g")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "var\\s+dt\\s+=\\s+new\\s+Date\\(\\),\\s+expiryTime\\s+=\\s+dt\\.setTime\\(\\s+dt\\.getTime\\(\\)\\s+\\+\\s+900000000")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "if\\s*\\(\\s*num\\s*===\\s*0\\s*\\)\\s*{\\s*return\\s*1;\\s*}\\s*else\\s*{\\s*return\\s+num\\s*\\*\\s*rFact\\(\\s*num\\s*-\\s*1")
   (notify "JS Virus"))
  (if (bodymask () "\\+=String\\.fromCharCode\\(parseInt\\(0\\+'x'")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "<script\\s+language=\"JavaScript\">\\s*parent\\.window\\.opener\\.location=\"http://vk\\.com")
   (notify "JS Virus"))
  (if (bodymask () "location\\.replace\\(['\"]{0,1}http://v5k45\\.ru")
   (notify "JS Virus"))
  (if
   (bodymask ()
    ";try{\\+\\+document\\.body}catch\\(q\\){aa=function\\(ff\\){for\\(i=0;i<z\\.length;i\\+\\+\\){za\\+=String\\[ff\\]\\(e\\(v\\+\\(z\\[i\\]\\)\\)-12\\);}};}")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "document\\.write\\s*\\(['\"]{0,1}<['\"]{0,1}\\s*\\+\\s*x\\[0\\]\\s*\\+\\s*['\"]{0,1} ['\"]{0,1}\\s*\\+\\s*x\\[4\\]\\s*\\+\\s*['\"]{0,1}>\\.['\"]{0,1}\\s*\\+x\\s*\\[2\\]\\s*\\+")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "if\\(t\\.length==2\\){z\\+=String\\.fromCharCode\\(parseInt\\(t\\)\\+")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "window\\.onload\\s*=\\s*function\\(\\)\\s*{\\s*if\\s*\\(document\\.cookie\\.indexOf\\(")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "\\.style\\.height\\s*=\\s*['\"]{0,1}0px['\"]{0,1};window\\.onload\\s*=\\s*function\\(\\)\\s*{document\\.cookie")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "\\.src=\\(['\"]{0,1}htps:['\"]{0,1}==document\\.location\\.protocol\\?['\"]{0,1}https://ssl['\"]{0,1}:['\"]{0,1}http://['\"]{0,1}\\)\\+")
   (notify "JS Virus"))
  (if (bodymask () "404\\.php['\"]{0,1}>\\s*</script>") (notify "JS Virus"))
  (if
   (bodymask ()
    "preg_match\\(['\"]{0,1}/sape/i['\"]{0,1}\\s*,\\s*\\$_SERVER\\[['\"]{0,1}HTTP_REFERER")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "div\\.innerHTML\\s*\\+=\\s*['\"]{0,1}<embed\\s+id=\"dummy2\"\\s+name=\"dummy2\"\\s+src")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "setTimeout\\(['\"]{0,1}addNewObject\\(\\)['\"]{0,1},\\d+\\);}}};addNewObject\\(\\)")
   (notify "JS Virus"))
  (if
   (bodymask () "\\(b=document\\)\\.head\\.appendChild\\(b\\.createElement")
   (notify "JS Virus"))
  (if (bodymask () "Chrome\\|iPad\\|iPhone\\|IEMobile") (notify "JS Virus"))
  (if (bodymask () "\\$:\\({}\\+\"\"\\)\\[\\$\\]") (notify "JS Virus"))
  (if (bodymask () "-\\s*PayPal\\s*</title>") (notify "JS Virus"))
  (if (bodymask () "-\\s*Privati\\s*</title>") (notify "JS Virus"))
  (if (bodymask () "<title>\\s*UniCredit") (notify "JS Virus"))
  (if (bodymask () "Bank\\s+of\\s+America") (notify "JS Virus"))
  (if (bodymask () "Alibaba&nbsp;Manufacturer") (notify "JS Virus"))
  (if (bodymask () "Hong\\s+Leong\\s+Online") (notify "JS Virus"))
  (if (bodymask () "Your\\s+account\\s+\\|\\s+Log\\s+in")
   (notify "JS Virus"))
  (if (bodymask () "Sign\\s+in\\s+to\\s+Yahoo") (notify "JS Virus"))
  (if (bodymask () BANCOLOMBIA) (notify "JS Virus"))
  (if (bodymask () "<title>\\s*Amazon") (notify "JS Virus"))
  (if (bodymask () "<title>\\s*Apple") (notify "JS Virus"))
  (if (bodymask () "<title>Google\\s+Secure") (notify "JS Virus"))
  (if (bodymask () "<title>Merak\\s+Mail\\s+Server") (notify "JS Virus"))
  (if (bodymask () "<title>Socket\\s+Webmail") (notify "JS Virus"))
  (if (bodymask () "<title>\\[L_QUERY\\]") (notify "JS Virus"))
  (if (bodymask () "<title>ANZ\\s+Internet\\s+Banking") (notify "JS Virus"))
  (if (bodymask () "com\\.websterbank\\.servlets\\.Login")
   (notify "JS Virus"))
  (if (bodymask () "{position:absolute;top:-9999px;}</style><div\\s+class=")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "if\\s*\\(\\(ua\\.indexOf\\(['\"]{0,1}chrome['\"]{0,1}\\)\\s*==\\s*-1\\s*&&\\s*ua\\.indexOf\\(\"win\"\\)\\s*!=\\s*-1\\)\\s*&&\\s*navigator\\.javaEnabled")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "parent\\.window\\.opener\\.location=['\"]{0,1}http://vk\\.com\\.")
   (notify "JS Virus"))
  (if (bodymask () "\\]\\.substr\\(0,1\\)\\);}}return this;},\\\\u00")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "javascript\\|head\\|toLowerCase\\|chrome\\|win\\|javaEnabled\\|appendChild")
   (notify "JS Virus"))
  (if (bodymask () "loadPNGData\\(strFile,") (notify "JS Virus"))
  (if (bodymask () "\\);if\\(!~\\(['\"]{0,1}") (notify "JS Virus"))
  (if (bodymask () "//\\s*Some\\.devices\\.are") (notify "JS Virus"))
  (if (bodymask () "window\\.onerror\\s*=\\s*killerrors")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "check_user_agent=\\[\\s*['\"]{0,1}Lunascape['\"]{0,1}\\s*,\\s*['\"]{0,1}iPhone['\"]{0,1}\\s*,\\s*['\"]{0,1}Macintosh")
   (notify "JS Virus"))
  (if
   (bodymask ()
    "document\\.write\\(['\"]{0,1}<['\"]{0,1}\\+['\"]{0,1}i['\"]{0,1}\\+['\"]{0,1}f['\"]{0,1}\\+['\"]{0,1}r['\"]{0,1}\\+['\"]{0,1}a['\"]{0,1}\\+['\"]{0,1}m['\"]{0,1}\\+['\"]{0,1}e")
   (notify "JS Virus"))
  (if (bodymask () "sexfromindia\\.com") (notify "JS Virus"))
  (if (bodymask () "filekx\\.com") (notify "JS Virus"))
  (if (bodymask () "stummann\\.net") (notify "JS Virus"))
  (if (bodymask () "http://xzx\\.pm") (notify "JS Virus"))
  (if (bodymask () "\\.hopto\\.me/jquery") (notify "JS Virus"))
  (if (bodymask () "mobi-go\\.in") (notify "JS Virus"))
  (if (bodymask () "bankofamerica\\.com") (notify "JS Virus"))
  (if (bodymask () "myfilestore\\.com") (notify "JS Virus"))
  (if (bodymask () "filestore72\\.info") (notify "JS Virus"))
  (if (bodymask () "file2store\\.info") (notify "JS Virus"))
  (if (bodymask () "url2short\\.info") (notify "JS Virus"))
  (if (bodymask () "filestore123\\.info") (notify "JS Virus"))
  (if (bodymask () "url123\\.info") (notify "JS Virus"))
  (if (bodymask () "dollarade\\.com") (notify "JS Virus"))
  (if (bodymask () "secclik\\.ru") (notify "JS Virus"))
  (if (bodymask () "moby-aa\\.ru") (notify "JS Virus"))
  (if (bodymask () "servload\\.ru") (notify "JS Virus"))
  (if (bodymask () "nnn\\.pm") (notify "JS Virus"))
  (if (bodymask () "stripos\\(navigator\\.userAgent\\s*,\\s*list_data\\[i")
   (notify "JS Virus"))
  (if (bodymask () "if\\s*\\(!see_user_agent\\(\\)") (notify "JS Virus"))
  (if (bodymask () "c\\.length\\);}return\\s*['\"]['\"];}if\\(!getCookie")
   (notify "JS Virus"))
  (if (bodymask () "@*extract\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "@*extract\\s*\\$") (notify "Suspicious Code"))
  (if (bodymask () "['\"]eval['\"]") (notify "Suspicious Code"))
  (if (bodymask () "['\"]base64_decode['\"]") (notify "Suspicious Code"))
  (if (bodymask () "['\"]create_function['\"]") (notify "Suspicious Code"))
  (if (bodymask () "['\"]assert['\"]") (notify "Suspicious Code"))
  (if (bodymask () "foreach\\s*\\(\\s*\\$emails\\s+as\\s+\\$email\\s*\\)")
   (notify "Suspicious Code"))
  (if (bodymask () Spammer) (notify "Suspicious Code"))
  (if (bodymask () "eval\\s*['\"\\(\\$]") (notify "Suspicious Code"))
  (if (bodymask () "assert\\s*['\"\\(\\$]") (notify "Suspicious Code"))
  (if (bodymask () "srpath://\\.\\./\\.\\./\\.\\./\\.\\.")
   (notify "Suspicious Code"))
  (if (bodymask () "phpinfo\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "SHOW\\s+DATABASES") (notify "Suspicious Code"))
  (if (bodymask () "\\bpopen\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "exec\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "\\bsystem\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "\\bpassthru\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "\\bproc_open\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "shell_exec\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "ini_restore\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "\\bdl\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "\\bsymlink\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "\\bchgrp\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "\\bini_set\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "\\bputenv\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "getmyuid\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "fsockopen\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "posix_setuid\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "posix_setsid\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "posix_setpgid\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "posix_kill\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "apache_child_terminate\\s*\\(")
   (notify "Suspicious Code"))
  (if (bodymask () "\\bchmod\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "\\bchdir\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "pcntl_exec\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "\\bvirtual\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "proc_close\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "proc_get_status\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "proc_terminate\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "proc_nice\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "getmygid\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "proc_getstatus\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "proc_close\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "escapeshellcmd\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "escapeshellarg\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "show_source\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "\\bpclose\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "safe_dir\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "ini_restore\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "chown\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "chgrp\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "shown_source\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "mysql_list_dbs\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "get_current_user\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "getmyid\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "\\bleak\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "pfsockopen\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "get_current_user\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "syslog\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "\\$default_use_ajax") (notify "Suspicious Code"))
  (if (bodymask () "eval\\s*\\(*\\s*unescape") (notify "Suspicious Code"))
  (if (bodymask () FLoodeR) (notify "Suspicious Code"))
  (if (bodymask () "document\\.write\\s*\\(\\s*unescape")
   (notify "Suspicious Code"))
  (if (bodymask () "\\bcopy\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "move_uploaded_file\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "\\.333333") (notify "Suspicious Code"))
  (if (bodymask () "\\.666666") (notify "Suspicious Code"))
  (if (bodymask () "round\\s*\\(*\\s*0\\s*\\)*") (notify "Suspicious Code"))
  (if
   (bodymask ()
    "copy\\s*\\(*\\s*\\$_FILES\\s*\\[\\s*['\"]{0,1}file['\"]{0,1}\\s*\\]\\[\\s*['\"]{0,1}tmp_name['\"]{0,1}\\s*\\]\\s*,\\s*\\$uploadfile")
   (notify "Suspicious Code"))
  (if
   (bodymask ()
    "move_uploaded_files\\s*\\(*\\s*\\$_FILES\\s*\\[\\s*['\"]{0,1}file['\"]{0,1}\\s*\\]\\[\\s*['\"]{0,1}tmp_name['\"]{0,1}\\s*\\]\\s*,\\s*\\$uploadfile")
   (notify "Suspicious Code"))
  (if (bodymask () "ini_get\\s*\\(\\s*['\"]{0,1}disable_functions['\"]{0,1}")
   (notify "Suspicious Code"))
  (if (bodymask () "UNION\\s+SELECT\\s+['\"]{0,1}0['\"]{0,1}")
   (notify "Suspicious Code"))
  (if (bodymask () "2\\s*>\\s*&1") (notify "Suspicious Code"))
  (if
   (bodymask ()
    "echo\\s*\\(*\\s*\\$_SERVER\\[['\"]{0,1}DOCUMENT_ROOT['\"]{0,1}\\]")
   (notify "Suspicious Code"))
  (if (bodymask () "=\\s*Array\\s*\\(*\\s*base64_decode\\s*\\(*")
   (notify "Suspicious Code"))
  (if (bodymask () "killall\\s+-\\d+") (notify "Suspicious Code"))
  (if (bodymask () eriuqer) (notify "Suspicious Code"))
  (if (bodymask () "touch\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () sshkeys) (notify "Suspicious Code"))
  (if (bodymask () @include) (notify "Suspicious Code"))
  (if (bodymask () @require) (notify "Suspicious Code"))
  (if
   (bodymask ()
    "if\\s*\\(mail\\s*\\(\\s*\\$to,\\s*\\$subject,\\s*\\$message,\\s*\\$headers")
   (notify "Suspicious Code"))
  (if (bodymask () "@ini_set\\s*\\(*['\"]{0,1}allow_url_fopen")
   (notify "Suspicious Code"))
  (if (bodymask () @file_get_contents) (notify "Suspicious Code"))
  (if (bodymask () file_put_contents) (notify "Suspicious Code"))
  (if (bodymask () "android\\s*\\|\\s*midp\\s*\\|\\s*j2me\\s*\\|\\s*symbian")
   (notify "Suspicious Code"))
  (if (bodymask () "@setcookie\\s*\\(*['\"]{0,1}hit")
   (notify "Suspicious Code"))
  (if (bodymask () @fileowner) (notify "Suspicious Code"))
  (if (bodymask () <kuku>) (notify "Suspicious Code"))
  (if (bodymask () sypex) (notify "Suspicious Code"))
  (if (bodymask () "\\$beecode") (notify "Suspicious Code"))
  (if (bodymask () Backdoor) (notify "Suspicious Code"))
  (if (bodymask () "php_uname\\s*\\(") (notify "Suspicious Code"))
  (if
   (bodymask ()
    "mail\\s*\\(*\\s*\\$to\\s*,\\s*\\$subj\\s*,\\s*\\$msg\\s*,\\s*\\$from")
   (notify "Suspicious Code"))
  (if (bodymask () "echo\\s*['\"]<script>\\s*alert\\(")
   (notify "Suspicious Code"))
  (if
   (bodymask ()
    "mail\\s*\\(*\\s*\\$send\\s*,\\s*\\$subject\\s*,\\s*\\$headers\\s*,\\s*\\$message")
   (notify "Suspicious Code"))
  (if
   (bodymask ()
    "mail\\s*\\(*\\s*\\$to\\s*,\\s*\\$subject\\s*,\\s*\\$message\\s*,\\s*\\$headers")
   (notify "Suspicious Code"))
  (if
   (bodymask ()
    "strpos\\s*\\(*\\s*\\$name\\s*,\\s*['\"]{0,1}HTTP_['\"]{0,1}\\s*\\)*\\s*!==\\s*0\\s*&&\\s*strpos\\s*\\(*\\s*\\$name\\s*,\\s*['\"]{0,1}REQUEST_")
   (notify "Suspicious Code"))
  (if
   (bodymask () "is_function_enabled\\s*\\(\\s*['\"]{0,1}ignore_user_abort")
   (notify "Suspicious Code"))
  (if (bodymask () "echo\\s*\\(*\\s*file_get_contents")
   (notify "Suspicious Code"))
  (if (bodymask () "echo\\s*\\(*['\"]{0,1}<script")
   (notify "Suspicious Code"))
  (if (bodymask () "print\\s*\\(*\\s*file_get_contents")
   (notify "Suspicious Code"))
  (if (bodymask () "print\\s*\\(*['\"]{0,1}<script")
   (notify "Suspicious Code"))
  (if
   (bodymask ()
    "<marquee\\s+style\\s*=\\s*['\"]{0,1}position\\s*:\\s*absolute\\s*;\\s*width\\s*:\\s*\\d+\\s*px\\s*")
   (notify "Suspicious Code"))
  (if (bodymask () "=\\s*['\"]{0,1}\\.\\./\\.\\./\\.\\./wp-config\\.php")
   (notify "Suspicious Code"))
  (if (bodymask () eggdrop) (notify "Suspicious Code"))
  (if (bodymask () rwxrwxrwx) (notify "Suspicious Code"))
  (if (bodymask () error_reporting) (notify "Suspicious Code"))
  (if (bodymask () "\\bcreate_function") (notify "Suspicious Code"))
  (if (bodymask () "{\\s*position\\s*:\\s*absolute;\\s*left\\s*:\\s*-")
   (notify "Suspicious Code"))
  (if (bodymask () "<script\\s+async") (notify "Suspicious Code"))
  (if
   (bodymask ()
    "_['\"]{0,1}\\s*\\]\\s*=\\s*Array\\s*\\(\\s*base64_decode\\s*\\(*\\s*['\"]{0,1}")
   (notify "Suspicious Code"))
  (if (bodymask () "AddType\\s+application/x-httpd-cgi")
   (notify "Suspicious Code"))
  (if (bodymask () "getenv\\s*\\(*\\s*['\"]{0,1}HTTP_COOKIE['\"]{0,1}")
   (notify "Suspicious Code"))
  (if (bodymask () "ignore_user_abort\\s*\\(*\\s*['\"]{0,1}1['\"]{0,1}")
   (notify "Suspicious Code"))
  (if (bodymask () "\\$_REQUEST\\s*\\[\\s*%22") (notify "Suspicious Code"))
  (if
   (bodymask () "url\\s*\\(['\"]{0,1}data\\s*:\\s*image/png;\\s*base64\\s*,")
   (notify "Suspicious Code"))
  (if
   (bodymask () "url\\s*\\(['\"]{0,1}data\\s*:\\s*image/gif;\\s*base64\\s*,")
   (notify "Suspicious Code"))
  (if (bodymask () ":\\s*url\\s*\\(\\s*['\"]{0,1}<\\?php")
   (notify "Suspicious Code"))
  (if (bodymask () </html>.+?<script) (notify "Suspicious Code"))
  (if (bodymask () </html>.+?<iframe) (notify "Suspicious Code"))
  (if
   (bodymask ()
    "(ftp_exec|system|shell_exec|passthru|popen|proc_open)\\s*['\"\\(\\$]")
   (notify "Suspicious Code"))
  (if (bodymask () "\\bmail\\s*\\(") (notify "Suspicious Code"))
  (if (bodymask () "file_get_contents\\s*\\(*\\s*['\"]{0,1}php://input")
   (notify "Suspicious Code"))
  (if
   (bodymask ()
    "<meta\\s+http-equiv=['\"]{0,1}Content-type['\"]{0,1}\\s+content=['\"]{0,1}text/html;\\s*charset=windows-1251['\"]{0,1}><body>")
   (notify "Suspicious Code"))
  (if
   (bodymask ()
    "=\\s*document\\.createElement\\(\\s*['\"]{0,1}script['\"]{0,1}\\s*\\);")
   (notify "Suspicious Code"))
  (if
   (bodymask ()
    "document\\.body\\.insertBefore\\(div,\\s*document\\.body\\.children\\[0\\]\\);")
   (notify "Suspicious Code"))
  (if
   (bodymask ()
    "<script\\s+type=\"text/javascript\"\\s+src=\"http://[a-zA-Z0-9_]+?\\.php\"></script>")
   (notify "Suspicious Code"))
  (if (bodymask () "echo\\s+['\"]{0,1}ok['\"]{0,1}")
   (notify "Suspicious Code"))
  (if (bodymask () /usr/sbin/sendmail) (notify "Suspicious Code"))
  (if (bodymask () /var/qmail/bin/sendmail) (notify "Suspicious Code"))))
